/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.mydsl.myDsl.ADD;
import org.xtext.example.mydsl.myDsl.ALIGNMENT;
import org.xtext.example.mydsl.myDsl.CELL;
import org.xtext.example.mydsl.myDsl.CELLRANGE;
import org.xtext.example.mydsl.myDsl.COLOR;
import org.xtext.example.mydsl.myDsl.Column;
import org.xtext.example.mydsl.myDsl.DIVID;
import org.xtext.example.mydsl.myDsl.MATHUNIT;
import org.xtext.example.mydsl.myDsl.MULT;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.NrColumns;
import org.xtext.example.mydsl.myDsl.PRIM;
import org.xtext.example.mydsl.myDsl.SUB;
import org.xtext.example.mydsl.myDsl.Table;
import org.xtext.example.mydsl.myDsl.VALUE;
import org.xtext.example.mydsl.myDsl.WIDTH;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == MyDslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case MyDslPackage.ADD:
				sequence_ADD(context, (ADD) semanticObject); 
				return; 
			case MyDslPackage.ALIGNMENT:
				sequence_ALIGNMENT(context, (ALIGNMENT) semanticObject); 
				return; 
			case MyDslPackage.CELL:
				sequence_CELL(context, (CELL) semanticObject); 
				return; 
			case MyDslPackage.CELLRANGE:
				sequence_CELLRANGE(context, (CELLRANGE) semanticObject); 
				return; 
			case MyDslPackage.COLOR:
				sequence_COLOR(context, (COLOR) semanticObject); 
				return; 
			case MyDslPackage.COLUMN:
				sequence_Column(context, (Column) semanticObject); 
				return; 
			case MyDslPackage.DIVID:
				sequence_DIVID(context, (DIVID) semanticObject); 
				return; 
			case MyDslPackage.MATHUNIT:
				sequence_MATHUNIT(context, (MATHUNIT) semanticObject); 
				return; 
			case MyDslPackage.MULT:
				sequence_MULT(context, (MULT) semanticObject); 
				return; 
			case MyDslPackage.NR_COLUMNS:
				sequence_NrColumns(context, (NrColumns) semanticObject); 
				return; 
			case MyDslPackage.PRIM:
				sequence_PRIM(context, (PRIM) semanticObject); 
				return; 
			case MyDslPackage.SUB:
				sequence_SUB(context, (SUB) semanticObject); 
				return; 
			case MyDslPackage.TABLE:
				sequence_Table(context, (Table) semanticObject); 
				return; 
			case MyDslPackage.VALUE:
				sequence_VALUE(context, (VALUE) semanticObject); 
				return; 
			case MyDslPackage.WIDTH:
				sequence_WIDTH(context, (WIDTH) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     ADD returns ADD
	 *
	 * Constraint:
	 *     (sub1=SUB sub2+=SUB*)
	 * </pre>
	 */
	protected void sequence_ADD(ISerializationContext context, ADD semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ALIGNMENT returns ALIGNMENT
	 *
	 * Constraint:
	 *     position=POSITION
	 * </pre>
	 */
	protected void sequence_ALIGNMENT(ISerializationContext context, ALIGNMENT semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.ALIGNMENT__POSITION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.ALIGNMENT__POSITION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getALIGNMENTAccess().getPositionPOSITIONTerminalRuleCall_1_0(), semanticObject.getPosition());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     CELLRANGE returns CELLRANGE
	 *
	 * Constraint:
	 *     (rangestart=CELLREF rangeend=CELLREF)
	 * </pre>
	 */
	protected void sequence_CELLRANGE(ISerializationContext context, CELLRANGE semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.CELLRANGE__RANGESTART) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.CELLRANGE__RANGESTART));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.CELLRANGE__RANGEEND) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.CELLRANGE__RANGEEND));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getCELLRANGEAccess().getRangestartCELLREFTerminalRuleCall_0_0(), semanticObject.getRangestart());
		feeder.accept(grammarAccess.getCELLRANGEAccess().getRangeendCELLREFTerminalRuleCall_2_0(), semanticObject.getRangeend());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     CELL returns CELL
	 *
	 * Constraint:
	 *     (number=INT color=COLOR? value=VALUE?)
	 * </pre>
	 */
	protected void sequence_CELL(ISerializationContext context, CELL semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     COLOR returns COLOR
	 *
	 * Constraint:
	 *     colorstring=COLORSTRING
	 * </pre>
	 */
	protected void sequence_COLOR(ISerializationContext context, COLOR semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.COLOR__COLORSTRING) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.COLOR__COLORSTRING));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getCOLORAccess().getColorstringCOLORSTRINGTerminalRuleCall_1_0(), semanticObject.getColorstring());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Column returns Column
	 *
	 * Constraint:
	 *     (
	 *         letter=LETTER 
	 *         width=WIDTH? 
	 *         alignment=ALIGNMENT? 
	 *         color=COLOR? 
	 *         line+=LINE* 
	 *         cell+=CELL*
	 *     )
	 * </pre>
	 */
	protected void sequence_Column(ISerializationContext context, Column semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     DIVID returns DIVID
	 *
	 * Constraint:
	 *     (prim1=PRIM prim2+=PRIM*)
	 * </pre>
	 */
	protected void sequence_DIVID(ISerializationContext context, DIVID semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     MATHUNIT returns MATHUNIT
	 *
	 * Constraint:
	 *     (number=INT | cellref=CELLREF)
	 * </pre>
	 */
	protected void sequence_MATHUNIT(ISerializationContext context, MATHUNIT semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     MULT returns MULT
	 *
	 * Constraint:
	 *     (divid1=DIVID divid2+=DIVID*)
	 * </pre>
	 */
	protected void sequence_MULT(ISerializationContext context, MULT semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     NrColumns returns NrColumns
	 *
	 * Constraint:
	 *     Nr+=INT
	 * </pre>
	 */
	protected void sequence_NrColumns(ISerializationContext context, NrColumns semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     PRIM returns PRIM
	 *
	 * Constraint:
	 *     (mathunit=MATHUNIT | add=ADD)
	 * </pre>
	 */
	protected void sequence_PRIM(ISerializationContext context, PRIM semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     SUB returns SUB
	 *
	 * Constraint:
	 *     (mult1=MULT mult2+=MULT*)
	 * </pre>
	 */
	protected void sequence_SUB(ISerializationContext context, SUB semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Table returns Table
	 *
	 * Constraint:
	 *     (name=ID nrColumns=NrColumns columns+=Column+)
	 * </pre>
	 */
	protected void sequence_Table(ISerializationContext context, Table semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     VALUE returns VALUE
	 *
	 * Constraint:
	 *     (string=STRING | expr=ADD | (math=MATH range=CELLRANGE))
	 * </pre>
	 */
	protected void sequence_VALUE(ISerializationContext context, VALUE semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     WIDTH returns WIDTH
	 *
	 * Constraint:
	 *     number=INT
	 * </pre>
	 */
	protected void sequence_WIDTH(ISerializationContext context, WIDTH semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.WIDTH__NUMBER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.WIDTH__NUMBER));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getWIDTHAccess().getNumberINTTerminalRuleCall_1_0(), semanticObject.getNumber());
		feeder.finish();
	}
	
	
}
