/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class TableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Table");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTableKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cNrColumnsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNrColumnsNrColumnsParserRuleCall_2_0 = (RuleCall)cNrColumnsAssignment_2.eContents().get(0);
		private final Assignment cColumnsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cColumnsColumnParserRuleCall_3_0 = (RuleCall)cColumnsAssignment_3.eContents().get(0);
		
		//Table: 'Table' name=ID nrColumns=NrColumns (columns+=Column)+;
		@Override public ParserRule getRule() { return rule; }
		
		//'Table' name=ID nrColumns=NrColumns (columns+=Column)+
		public Group getGroup() { return cGroup; }
		
		//'Table'
		public Keyword getTableKeyword_0() { return cTableKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//nrColumns=NrColumns
		public Assignment getNrColumnsAssignment_2() { return cNrColumnsAssignment_2; }
		
		//NrColumns
		public RuleCall getNrColumnsNrColumnsParserRuleCall_2_0() { return cNrColumnsNrColumnsParserRuleCall_2_0; }
		
		//(columns+=Column)+
		public Assignment getColumnsAssignment_3() { return cColumnsAssignment_3; }
		
		//Column
		public RuleCall getColumnsColumnParserRuleCall_3_0() { return cColumnsColumnParserRuleCall_3_0; }
	}
	public class ColumnElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Column");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cColumnKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cLetterAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLetterLETTERTerminalRuleCall_1_0 = (RuleCall)cLetterAssignment_1.eContents().get(0);
		private final Assignment cWidthAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cWidthWIDTHParserRuleCall_2_0 = (RuleCall)cWidthAssignment_2.eContents().get(0);
		private final Assignment cAlignmentAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cAlignmentALIGNMENTParserRuleCall_3_0 = (RuleCall)cAlignmentAssignment_3.eContents().get(0);
		private final Assignment cColorAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cColorCOLORParserRuleCall_4_0 = (RuleCall)cColorAssignment_4.eContents().get(0);
		private final Assignment cLineAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cLineLINETerminalRuleCall_5_0 = (RuleCall)cLineAssignment_5.eContents().get(0);
		private final Assignment cCellAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cCellCELLParserRuleCall_6_0 = (RuleCall)cCellAssignment_6.eContents().get(0);
		
		//Column: 'Column' letter=LETTER (width=WIDTH)? (alignment=ALIGNMENT)? (color=COLOR)? (line+=LINE)* (cell+=CELL)* ;
		@Override public ParserRule getRule() { return rule; }
		
		//'Column' letter=LETTER (width=WIDTH)? (alignment=ALIGNMENT)? (color=COLOR)? (line+=LINE)* (cell+=CELL)*
		public Group getGroup() { return cGroup; }
		
		//'Column'
		public Keyword getColumnKeyword_0() { return cColumnKeyword_0; }
		
		//letter=LETTER
		public Assignment getLetterAssignment_1() { return cLetterAssignment_1; }
		
		//LETTER
		public RuleCall getLetterLETTERTerminalRuleCall_1_0() { return cLetterLETTERTerminalRuleCall_1_0; }
		
		//(width=WIDTH)?
		public Assignment getWidthAssignment_2() { return cWidthAssignment_2; }
		
		//WIDTH
		public RuleCall getWidthWIDTHParserRuleCall_2_0() { return cWidthWIDTHParserRuleCall_2_0; }
		
		//(alignment=ALIGNMENT)?
		public Assignment getAlignmentAssignment_3() { return cAlignmentAssignment_3; }
		
		//ALIGNMENT
		public RuleCall getAlignmentALIGNMENTParserRuleCall_3_0() { return cAlignmentALIGNMENTParserRuleCall_3_0; }
		
		//(color=COLOR)?
		public Assignment getColorAssignment_4() { return cColorAssignment_4; }
		
		//COLOR
		public RuleCall getColorCOLORParserRuleCall_4_0() { return cColorCOLORParserRuleCall_4_0; }
		
		//(line+=LINE)*
		public Assignment getLineAssignment_5() { return cLineAssignment_5; }
		
		//LINE
		public RuleCall getLineLINETerminalRuleCall_5_0() { return cLineLINETerminalRuleCall_5_0; }
		
		//(cell+=CELL)*
		public Assignment getCellAssignment_6() { return cCellAssignment_6; }
		
		//CELL
		public RuleCall getCellCELLParserRuleCall_6_0() { return cCellCELLParserRuleCall_6_0; }
	}
	public class NrColumnsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.NrColumns");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cColumnsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNrAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNrINTTerminalRuleCall_1_0 = (RuleCall)cNrAssignment_1.eContents().get(0);
		
		//NrColumns: 'Columns' Nr+=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'Columns' Nr+=INT
		public Group getGroup() { return cGroup; }
		
		//'Columns'
		public Keyword getColumnsKeyword_0() { return cColumnsKeyword_0; }
		
		//Nr+=INT
		public Assignment getNrAssignment_1() { return cNrAssignment_1; }
		
		//INT
		public RuleCall getNrINTTerminalRuleCall_1_0() { return cNrINTTerminalRuleCall_1_0; }
	}
	public class WIDTHElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.WIDTH");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWidthKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNumberAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNumberINTTerminalRuleCall_1_0 = (RuleCall)cNumberAssignment_1.eContents().get(0);
		private final Keyword cCmKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//WIDTH: 'Width' number=INT 'cm';
		@Override public ParserRule getRule() { return rule; }
		
		//'Width' number=INT 'cm'
		public Group getGroup() { return cGroup; }
		
		//'Width'
		public Keyword getWidthKeyword_0() { return cWidthKeyword_0; }
		
		//number=INT
		public Assignment getNumberAssignment_1() { return cNumberAssignment_1; }
		
		//INT
		public RuleCall getNumberINTTerminalRuleCall_1_0() { return cNumberINTTerminalRuleCall_1_0; }
		
		//'cm'
		public Keyword getCmKeyword_2() { return cCmKeyword_2; }
	}
	public class ALIGNMENTElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.ALIGNMENT");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAlignmentKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cPositionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPositionPOSITIONTerminalRuleCall_1_0 = (RuleCall)cPositionAssignment_1.eContents().get(0);
		
		//ALIGNMENT: 'Alignment' position=POSITION;
		@Override public ParserRule getRule() { return rule; }
		
		//'Alignment' position=POSITION
		public Group getGroup() { return cGroup; }
		
		//'Alignment'
		public Keyword getAlignmentKeyword_0() { return cAlignmentKeyword_0; }
		
		//position=POSITION
		public Assignment getPositionAssignment_1() { return cPositionAssignment_1; }
		
		//POSITION
		public RuleCall getPositionPOSITIONTerminalRuleCall_1_0() { return cPositionPOSITIONTerminalRuleCall_1_0; }
	}
	public class COLORElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.COLOR");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cColorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cColorstringAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cColorstringCOLORSTRINGTerminalRuleCall_1_0 = (RuleCall)cColorstringAssignment_1.eContents().get(0);
		
		//COLOR: 'Color' colorstring=COLORSTRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'Color' colorstring=COLORSTRING
		public Group getGroup() { return cGroup; }
		
		//'Color'
		public Keyword getColorKeyword_0() { return cColorKeyword_0; }
		
		//colorstring=COLORSTRING
		public Assignment getColorstringAssignment_1() { return cColorstringAssignment_1; }
		
		//COLORSTRING
		public RuleCall getColorstringCOLORSTRINGTerminalRuleCall_1_0() { return cColorstringCOLORSTRINGTerminalRuleCall_1_0; }
	}
	public class CELLElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.CELL");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCellKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNumberAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNumberINTTerminalRuleCall_1_0 = (RuleCall)cNumberAssignment_1.eContents().get(0);
		private final Assignment cColorAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cColorCOLORParserRuleCall_2_0 = (RuleCall)cColorAssignment_2.eContents().get(0);
		private final Assignment cValueAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cValueVALUEParserRuleCall_3_0 = (RuleCall)cValueAssignment_3.eContents().get(0);
		
		//CELL: 'Cell' number=INT color=COLOR? value=VALUE?;
		@Override public ParserRule getRule() { return rule; }
		
		//'Cell' number=INT color=COLOR? value=VALUE?
		public Group getGroup() { return cGroup; }
		
		//'Cell'
		public Keyword getCellKeyword_0() { return cCellKeyword_0; }
		
		//number=INT
		public Assignment getNumberAssignment_1() { return cNumberAssignment_1; }
		
		//INT
		public RuleCall getNumberINTTerminalRuleCall_1_0() { return cNumberINTTerminalRuleCall_1_0; }
		
		//color=COLOR?
		public Assignment getColorAssignment_2() { return cColorAssignment_2; }
		
		//COLOR
		public RuleCall getColorCOLORParserRuleCall_2_0() { return cColorCOLORParserRuleCall_2_0; }
		
		//value=VALUE?
		public Assignment getValueAssignment_3() { return cValueAssignment_3; }
		
		//VALUE
		public RuleCall getValueVALUEParserRuleCall_3_0() { return cValueVALUEParserRuleCall_3_0; }
	}
	public class MATHElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.MATH");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cSumKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cMeanKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cMedianKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		
		//MATH: 'sum' | 'mean' |'median';
		@Override public ParserRule getRule() { return rule; }
		
		//'sum' | 'mean' |'median'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'sum'
		public Keyword getSumKeyword_0() { return cSumKeyword_0; }
		
		//'mean'
		public Keyword getMeanKeyword_1() { return cMeanKeyword_1; }
		
		//'median'
		public Keyword getMedianKeyword_2() { return cMedianKeyword_2; }
	}
	public class VALUEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.VALUE");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cValueKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Assignment cStringAssignment_1_0 = (Assignment)cAlternatives_1.eContents().get(0);
		private final RuleCall cStringSTRINGTerminalRuleCall_1_0_0 = (RuleCall)cStringAssignment_1_0.eContents().get(0);
		private final Assignment cExprAssignment_1_1 = (Assignment)cAlternatives_1.eContents().get(1);
		private final RuleCall cExprADDParserRuleCall_1_1_0 = (RuleCall)cExprAssignment_1_1.eContents().get(0);
		private final Group cGroup_1_2 = (Group)cAlternatives_1.eContents().get(2);
		private final Assignment cMathAssignment_1_2_0 = (Assignment)cGroup_1_2.eContents().get(0);
		private final RuleCall cMathMATHParserRuleCall_1_2_0_0 = (RuleCall)cMathAssignment_1_2_0.eContents().get(0);
		private final Assignment cRangeAssignment_1_2_1 = (Assignment)cGroup_1_2.eContents().get(1);
		private final RuleCall cRangeCELLRANGEParserRuleCall_1_2_1_0 = (RuleCall)cRangeAssignment_1_2_1.eContents().get(0);
		
		//VALUE: 'Value' (string=STRING | expr=ADD | math=MATH range=CELLRANGE);
		@Override public ParserRule getRule() { return rule; }
		
		//'Value' (string=STRING | expr=ADD | math=MATH range=CELLRANGE)
		public Group getGroup() { return cGroup; }
		
		//'Value'
		public Keyword getValueKeyword_0() { return cValueKeyword_0; }
		
		//(string=STRING | expr=ADD | math=MATH range=CELLRANGE)
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//string=STRING
		public Assignment getStringAssignment_1_0() { return cStringAssignment_1_0; }
		
		//STRING
		public RuleCall getStringSTRINGTerminalRuleCall_1_0_0() { return cStringSTRINGTerminalRuleCall_1_0_0; }
		
		//expr=ADD
		public Assignment getExprAssignment_1_1() { return cExprAssignment_1_1; }
		
		//ADD
		public RuleCall getExprADDParserRuleCall_1_1_0() { return cExprADDParserRuleCall_1_1_0; }
		
		//math=MATH range=CELLRANGE
		public Group getGroup_1_2() { return cGroup_1_2; }
		
		//math=MATH
		public Assignment getMathAssignment_1_2_0() { return cMathAssignment_1_2_0; }
		
		//MATH
		public RuleCall getMathMATHParserRuleCall_1_2_0_0() { return cMathMATHParserRuleCall_1_2_0_0; }
		
		//range=CELLRANGE
		public Assignment getRangeAssignment_1_2_1() { return cRangeAssignment_1_2_1; }
		
		//CELLRANGE
		public RuleCall getRangeCELLRANGEParserRuleCall_1_2_1_0() { return cRangeCELLRANGEParserRuleCall_1_2_1_0; }
	}
	public class ADDElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.ADD");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cSub1Assignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cSub1SUBParserRuleCall_0_0 = (RuleCall)cSub1Assignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cPlusSignKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cSub2Assignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cSub2SUBParserRuleCall_1_1_0 = (RuleCall)cSub2Assignment_1_1.eContents().get(0);
		
		//ADD: sub1=SUB ('+' sub2+=SUB)*;
		@Override public ParserRule getRule() { return rule; }
		
		//sub1=SUB ('+' sub2+=SUB)*
		public Group getGroup() { return cGroup; }
		
		//sub1=SUB
		public Assignment getSub1Assignment_0() { return cSub1Assignment_0; }
		
		//SUB
		public RuleCall getSub1SUBParserRuleCall_0_0() { return cSub1SUBParserRuleCall_0_0; }
		
		//('+' sub2+=SUB)*
		public Group getGroup_1() { return cGroup_1; }
		
		//'+'
		public Keyword getPlusSignKeyword_1_0() { return cPlusSignKeyword_1_0; }
		
		//sub2+=SUB
		public Assignment getSub2Assignment_1_1() { return cSub2Assignment_1_1; }
		
		//SUB
		public RuleCall getSub2SUBParserRuleCall_1_1_0() { return cSub2SUBParserRuleCall_1_1_0; }
	}
	public class SUBElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.SUB");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cMult1Assignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cMult1MULTParserRuleCall_0_0 = (RuleCall)cMult1Assignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cMult2Assignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cMult2MULTParserRuleCall_1_1_0 = (RuleCall)cMult2Assignment_1_1.eContents().get(0);
		
		//SUB: mult1=MULT ('-' mult2+=MULT)*;
		@Override public ParserRule getRule() { return rule; }
		
		//mult1=MULT ('-' mult2+=MULT)*
		public Group getGroup() { return cGroup; }
		
		//mult1=MULT
		public Assignment getMult1Assignment_0() { return cMult1Assignment_0; }
		
		//MULT
		public RuleCall getMult1MULTParserRuleCall_0_0() { return cMult1MULTParserRuleCall_0_0; }
		
		//('-' mult2+=MULT)*
		public Group getGroup_1() { return cGroup_1; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_1_0() { return cHyphenMinusKeyword_1_0; }
		
		//mult2+=MULT
		public Assignment getMult2Assignment_1_1() { return cMult2Assignment_1_1; }
		
		//MULT
		public RuleCall getMult2MULTParserRuleCall_1_1_0() { return cMult2MULTParserRuleCall_1_1_0; }
	}
	public class MULTElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.MULT");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDivid1Assignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDivid1DIVIDParserRuleCall_0_0 = (RuleCall)cDivid1Assignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cAsteriskKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cDivid2Assignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cDivid2DIVIDParserRuleCall_1_1_0 = (RuleCall)cDivid2Assignment_1_1.eContents().get(0);
		
		//MULT: divid1=DIVID ('*' divid2+=DIVID)*;
		@Override public ParserRule getRule() { return rule; }
		
		//divid1=DIVID ('*' divid2+=DIVID)*
		public Group getGroup() { return cGroup; }
		
		//divid1=DIVID
		public Assignment getDivid1Assignment_0() { return cDivid1Assignment_0; }
		
		//DIVID
		public RuleCall getDivid1DIVIDParserRuleCall_0_0() { return cDivid1DIVIDParserRuleCall_0_0; }
		
		//('*' divid2+=DIVID)*
		public Group getGroup_1() { return cGroup_1; }
		
		//'*'
		public Keyword getAsteriskKeyword_1_0() { return cAsteriskKeyword_1_0; }
		
		//divid2+=DIVID
		public Assignment getDivid2Assignment_1_1() { return cDivid2Assignment_1_1; }
		
		//DIVID
		public RuleCall getDivid2DIVIDParserRuleCall_1_1_0() { return cDivid2DIVIDParserRuleCall_1_1_0; }
	}
	public class DIVIDElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.DIVID");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPrim1Assignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cPrim1PRIMParserRuleCall_0_0 = (RuleCall)cPrim1Assignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cSolidusKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cPrim2Assignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cPrim2PRIMParserRuleCall_1_1_0 = (RuleCall)cPrim2Assignment_1_1.eContents().get(0);
		
		//DIVID: prim1=PRIM ('/' prim2+=PRIM)*;
		@Override public ParserRule getRule() { return rule; }
		
		//prim1=PRIM ('/' prim2+=PRIM)*
		public Group getGroup() { return cGroup; }
		
		//prim1=PRIM
		public Assignment getPrim1Assignment_0() { return cPrim1Assignment_0; }
		
		//PRIM
		public RuleCall getPrim1PRIMParserRuleCall_0_0() { return cPrim1PRIMParserRuleCall_0_0; }
		
		//('/' prim2+=PRIM)*
		public Group getGroup_1() { return cGroup_1; }
		
		//'/'
		public Keyword getSolidusKeyword_1_0() { return cSolidusKeyword_1_0; }
		
		//prim2+=PRIM
		public Assignment getPrim2Assignment_1_1() { return cPrim2Assignment_1_1; }
		
		//PRIM
		public RuleCall getPrim2PRIMParserRuleCall_1_1_0() { return cPrim2PRIMParserRuleCall_1_1_0; }
	}
	public class PRIMElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.PRIM");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cMathunitAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cMathunitMATHUNITParserRuleCall_0_0 = (RuleCall)cMathunitAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cAddAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cAddADDParserRuleCall_1_1_0 = (RuleCall)cAddAssignment_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		
		//PRIM: mathunit=MATHUNIT | ('(' add=ADD ')');
		@Override public ParserRule getRule() { return rule; }
		
		//mathunit=MATHUNIT | ('(' add=ADD ')')
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//mathunit=MATHUNIT
		public Assignment getMathunitAssignment_0() { return cMathunitAssignment_0; }
		
		//MATHUNIT
		public RuleCall getMathunitMATHUNITParserRuleCall_0_0() { return cMathunitMATHUNITParserRuleCall_0_0; }
		
		//('(' add=ADD ')')
		public Group getGroup_1() { return cGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//add=ADD
		public Assignment getAddAssignment_1_1() { return cAddAssignment_1_1; }
		
		//ADD
		public RuleCall getAddADDParserRuleCall_1_1_0() { return cAddADDParserRuleCall_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_2() { return cRightParenthesisKeyword_1_2; }
	}
	public class CELLRANGEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.CELLRANGE");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cRangestartAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cRangestartCELLREFTerminalRuleCall_0_0 = (RuleCall)cRangestartAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cRangeendAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cRangeendCELLREFTerminalRuleCall_2_0 = (RuleCall)cRangeendAssignment_2.eContents().get(0);
		
		////MATHOPS: '+' | '-' |'*' |'/';
		////CELLREF: letter=LETTER number=INT;
		//CELLRANGE: rangestart=CELLREF ':' rangeend=CELLREF;
		@Override public ParserRule getRule() { return rule; }
		
		//rangestart=CELLREF ':' rangeend=CELLREF
		public Group getGroup() { return cGroup; }
		
		//rangestart=CELLREF
		public Assignment getRangestartAssignment_0() { return cRangestartAssignment_0; }
		
		//CELLREF
		public RuleCall getRangestartCELLREFTerminalRuleCall_0_0() { return cRangestartCELLREFTerminalRuleCall_0_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//rangeend=CELLREF
		public Assignment getRangeendAssignment_2() { return cRangeendAssignment_2; }
		
		//CELLREF
		public RuleCall getRangeendCELLREFTerminalRuleCall_2_0() { return cRangeendCELLREFTerminalRuleCall_2_0; }
	}
	public class MATHUNITElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.MATHUNIT");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cNumberAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cNumberINTTerminalRuleCall_0_0 = (RuleCall)cNumberAssignment_0.eContents().get(0);
		private final Assignment cCellrefAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cCellrefCELLREFTerminalRuleCall_1_0 = (RuleCall)cCellrefAssignment_1.eContents().get(0);
		
		//MATHUNIT: number=INT | cellref=CELLREF;
		@Override public ParserRule getRule() { return rule; }
		
		//number=INT | cellref=CELLREF
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//number=INT
		public Assignment getNumberAssignment_0() { return cNumberAssignment_0; }
		
		//INT
		public RuleCall getNumberINTTerminalRuleCall_0_0() { return cNumberINTTerminalRuleCall_0_0; }
		
		//cellref=CELLREF
		public Assignment getCellrefAssignment_1() { return cCellrefAssignment_1; }
		
		//CELLREF
		public RuleCall getCellrefCELLREFTerminalRuleCall_1_0() { return cCellrefCELLREFTerminalRuleCall_1_0; }
	}
	
	
	private final TableElements pTable;
	private final TerminalRule tLINE;
	private final TerminalRule tPOSITION;
	private final TerminalRule tLETTER;
	private final TerminalRule tALPHANUMERIC;
	private final TerminalRule tCOLORSTRING;
	private final TerminalRule tBOOLEAN;
	private final TerminalRule tCELLREF;
	private final ColumnElements pColumn;
	private final NrColumnsElements pNrColumns;
	private final WIDTHElements pWIDTH;
	private final ALIGNMENTElements pALIGNMENT;
	private final COLORElements pCOLOR;
	private final CELLElements pCELL;
	private final MATHElements pMATH;
	private final VALUEElements pVALUE;
	private final ADDElements pADD;
	private final SUBElements pSUB;
	private final MULTElements pMULT;
	private final DIVIDElements pDIVID;
	private final PRIMElements pPRIM;
	private final CELLRANGEElements pCELLRANGE;
	private final MATHUNITElements pMATHUNIT;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pTable = new TableElements();
		this.tLINE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.LINE");
		this.tPOSITION = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.POSITION");
		this.tLETTER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.LETTER");
		this.tALPHANUMERIC = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.ALPHANUMERIC");
		this.tCOLORSTRING = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.COLORSTRING");
		this.tBOOLEAN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.BOOLEAN");
		this.tCELLREF = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.CELLREF");
		this.pColumn = new ColumnElements();
		this.pNrColumns = new NrColumnsElements();
		this.pWIDTH = new WIDTHElements();
		this.pALIGNMENT = new ALIGNMENTElements();
		this.pCOLOR = new COLORElements();
		this.pCELL = new CELLElements();
		this.pMATH = new MATHElements();
		this.pVALUE = new VALUEElements();
		this.pADD = new ADDElements();
		this.pSUB = new SUBElements();
		this.pMULT = new MULTElements();
		this.pDIVID = new DIVIDElements();
		this.pPRIM = new PRIMElements();
		this.pCELLRANGE = new CELLRANGEElements();
		this.pMATHUNIT = new MATHUNITElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Table: 'Table' name=ID nrColumns=NrColumns (columns+=Column)+;
	public TableElements getTableAccess() {
		return pTable;
	}
	
	public ParserRule getTableRule() {
		return getTableAccess().getRule();
	}
	
	////terminal NUMBER: ('0'..'9');
	//terminal LINE: 'rightVerticalLine'|'leftVertical' BOOLEAN;
	public TerminalRule getLINERule() {
		return tLINE;
	}
	
	//terminal POSITION: 'left' | 'center' | 'right';
	public TerminalRule getPOSITIONRule() {
		return tPOSITION;
	}
	
	//terminal LETTER: ('a'..'z'|'A'..'Z');
	public TerminalRule getLETTERRule() {
		return tLETTER;
	}
	
	//terminal ALPHANUMERIC: INT | LETTER;
	public TerminalRule getALPHANUMERICRule() {
		return tALPHANUMERIC;
	}
	
	//terminal COLORSTRING: LETTER+ | '#' ALPHANUMERIC+ | 'RGB('INT+','INT+','INT+')';
	public TerminalRule getCOLORSTRINGRule() {
		return tCOLORSTRING;
	}
	
	//terminal BOOLEAN: 'true' | 'false';
	public TerminalRule getBOOLEANRule() {
		return tBOOLEAN;
	}
	
	//terminal CELLREF: ('A'..'Z')('0'..'9');
	public TerminalRule getCELLREFRule() {
		return tCELLREF;
	}
	
	//Column: 'Column' letter=LETTER (width=WIDTH)? (alignment=ALIGNMENT)? (color=COLOR)? (line+=LINE)* (cell+=CELL)* ;
	public ColumnElements getColumnAccess() {
		return pColumn;
	}
	
	public ParserRule getColumnRule() {
		return getColumnAccess().getRule();
	}
	
	//NrColumns: 'Columns' Nr+=INT;
	public NrColumnsElements getNrColumnsAccess() {
		return pNrColumns;
	}
	
	public ParserRule getNrColumnsRule() {
		return getNrColumnsAccess().getRule();
	}
	
	//WIDTH: 'Width' number=INT 'cm';
	public WIDTHElements getWIDTHAccess() {
		return pWIDTH;
	}
	
	public ParserRule getWIDTHRule() {
		return getWIDTHAccess().getRule();
	}
	
	//ALIGNMENT: 'Alignment' position=POSITION;
	public ALIGNMENTElements getALIGNMENTAccess() {
		return pALIGNMENT;
	}
	
	public ParserRule getALIGNMENTRule() {
		return getALIGNMENTAccess().getRule();
	}
	
	//COLOR: 'Color' colorstring=COLORSTRING;
	public COLORElements getCOLORAccess() {
		return pCOLOR;
	}
	
	public ParserRule getCOLORRule() {
		return getCOLORAccess().getRule();
	}
	
	//CELL: 'Cell' number=INT color=COLOR? value=VALUE?;
	public CELLElements getCELLAccess() {
		return pCELL;
	}
	
	public ParserRule getCELLRule() {
		return getCELLAccess().getRule();
	}
	
	//MATH: 'sum' | 'mean' |'median';
	public MATHElements getMATHAccess() {
		return pMATH;
	}
	
	public ParserRule getMATHRule() {
		return getMATHAccess().getRule();
	}
	
	//VALUE: 'Value' (string=STRING | expr=ADD | math=MATH range=CELLRANGE);
	public VALUEElements getVALUEAccess() {
		return pVALUE;
	}
	
	public ParserRule getVALUERule() {
		return getVALUEAccess().getRule();
	}
	
	//ADD: sub1=SUB ('+' sub2+=SUB)*;
	public ADDElements getADDAccess() {
		return pADD;
	}
	
	public ParserRule getADDRule() {
		return getADDAccess().getRule();
	}
	
	//SUB: mult1=MULT ('-' mult2+=MULT)*;
	public SUBElements getSUBAccess() {
		return pSUB;
	}
	
	public ParserRule getSUBRule() {
		return getSUBAccess().getRule();
	}
	
	//MULT: divid1=DIVID ('*' divid2+=DIVID)*;
	public MULTElements getMULTAccess() {
		return pMULT;
	}
	
	public ParserRule getMULTRule() {
		return getMULTAccess().getRule();
	}
	
	//DIVID: prim1=PRIM ('/' prim2+=PRIM)*;
	public DIVIDElements getDIVIDAccess() {
		return pDIVID;
	}
	
	public ParserRule getDIVIDRule() {
		return getDIVIDAccess().getRule();
	}
	
	//PRIM: mathunit=MATHUNIT | ('(' add=ADD ')');
	public PRIMElements getPRIMAccess() {
		return pPRIM;
	}
	
	public ParserRule getPRIMRule() {
		return getPRIMAccess().getRule();
	}
	
	////MATHOPS: '+' | '-' |'*' |'/';
	////CELLREF: letter=LETTER number=INT;
	//CELLRANGE: rangestart=CELLREF ':' rangeend=CELLREF;
	public CELLRANGEElements getCELLRANGEAccess() {
		return pCELLRANGE;
	}
	
	public ParserRule getCELLRANGERule() {
		return getCELLRANGEAccess().getRule();
	}
	
	//MATHUNIT: number=INT | cellref=CELLREF;
	public MATHUNITElements getMATHUNITAccess() {
		return pMATHUNIT;
	}
	
	public ParserRule getMATHUNITRule() {
		return getMATHUNITAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
