/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.mydsl.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MyDslIdeModule extends AbstractMyDslIdeModule {
}
