grammar org.xtext.example.mydsl.MyDsl with org.eclipse.xtext.common.Terminals

generate myDsl "http://www.xtext.org/example/mydsl/MyDsl"

//SystemRoot: tables+=Table+;
SystemRoot: (vars+=VarDeclaration)* tables+=Table+;

Table: 'Table' name=ID (vars+=VarDeclaration)* (columns+=Column)+;

VarDeclaration: 'var' type=('int' | 'double' | 'string' | 'boolean') name=ID '=' value=AnyValue;

AnyValue: numVal=Exp | strVal=STRING | boolVal=BOOLEAN;

terminal LINE: 'rightVerticalLine' | 'leftVertical' BOOLEAN;
terminal POSITION: 'left' | 'center' | 'right';
terminal LETTER: ('A'..'Z');
terminal ALPHANUMERIC: INT | LETTER;

//terminal NUMBER: INT;
NUMBER: INT (('.'|',') INT)?;
// Added CellIndex for Individual Extension.
CELLINDEX: INT;

terminal COLORSTRING: LETTER+ | '#' ALPHANUMERIC+ | 'RGB('INT+','INT+','INT+')';
terminal BOOLEAN: 'true' | 'false';
//terminal CELLREF: ('A'..'Z')('0'..'9');

Column: 'Column' name=LETTER (vars+=VarDeclaration)* (width=WIDTH)? (alignment=ALIGNMENT)? (color=COLOR)? (line+=LINE)* (cell+=CELL)*;
//NrColumns: 'Columns' Nr=INT;
WIDTH: 'Width' number=INT 'cm';
ALIGNMENT: 'Alignment' position=POSITION;
COLOR: 'Color' colorstring=COLORSTRING;

//CELL: 'Cell' name=NUMBER color=COLOR? value=VALUE?;
CELL: 'Cell' name=CELLINDEX color=COLOR? value=VALUE?;

//MATHUNIT: number=NUMBER | cellRef=[CELL|CELLREF];
MATHUNIT: number=NUMBER | cellRef=[CELL|CELLREF] | varRef=[VarDeclaration|ID];
CELLREF: LETTER "." CELLINDEX;

MATH: 'sum' | 'mean' | 'median';
VALUE: 'Value' (string=STRING | expr=Exp | math=MATH '(' range=CELLRANGE ')');

Exp returns Expression:
    Term (
        ({Plus.left=current} '+' right=Term) |
        ({Minus.left=current} '-' right=Term)
    )*;

Term returns Expression:
    Factor (
        ({Mult.left=current} '*' right=Factor) |
        ({Div.left=current} '/' right=Factor)
    )*;

Factor returns Expression:
    MATHUNIT |
    '(' Exp ')';

CELLRANGE: rangestart=CELLREF ':' rangeend=CELLREF;
