grammar org.xtext.example.mydsl.MyDsl with org.eclipse.xtext.common.Terminals

generate myDsl "http://www.xtext.org/example/mydsl/MyDsl"

// === ENTRY POINT ===
//SYSTEMROOT: tables+=TABLE+;
SYSTEMROOT: (variables+=VARDECLARATION)* tables+=TABLE+;

// === VARIABLER ===
VARDECLARATION: 'var' type=('int' | 'double' | 'string' | 'boolean') name=ID '=' value=ANYVALUE;

ANYVALUE: numberValue=Exp | stringValue=STRING | booleanValue=BOOLEAN;

// === TABLE ===
TABLE: 'Table' name=ID (variables+=VARDECLARATION)* (columns+=COLUMN)+;

// === KOLONNE ===
COLUMN: 'Column' name=LETTER (variables+=VARDECLARATION)* (width=WIDTH)? (alignment=ALIGNMENT)? (color=COLOR)? (line+=LINE)* (cell+=CELL)*;
//NrColumns: 'Columns' Nr=INT;
WIDTH: 'Width' number=INT 'cm';
ALIGNMENT: 'Alignment' position=POSITION;
COLOR: 'Color' colorstring=COLORSTRING;

// === CELLE ===
//CELL: 'Cell' name=NUMBER color=COLOR? value=VALUE?;
CELL: 'Cell' name=CELLINDEX color=COLOR? value=VALUE?;

// Added CellIndex for Individual Extension.
CELLINDEX: INT;

VALUE: 'Value' (string=STRING | expr=Exp | math=MATH '(' range=CELLRANGE ')');

MATH: 'sum' | 'mean' | 'median';

CELLRANGE: rangestart=CELLREF ':' rangeend=CELLREF;

CELLREF: LETTER "." CELLINDEX;

//terminal NUMBER: INT;
NUMBER: INT (('.'|',') INT)?;

// === MATEMATIK / UDTRYK ===
//MATHUNIT: number=NUMBER | cellRef=[CELL|CELLREF];
MATHUNIT: number=NUMBER | cellRef=[CELL|CELLREF] | varRef=[VARDECLARATION|ID];

Exp returns Expression:
    Term (
        ({Plus.left=current} '+' right=Term) |
        ({Minus.left=current} '-' right=Term)
    )*;

Term returns Expression:
    Factor (
        ({Mult.left=current} '*' right=Factor) |
        ({Div.left=current} '/' right=Factor)
    )*;

Factor returns Expression:
    MATHUNIT |
    '(' Exp ')';

// === TERMINALER ===
terminal BOOLEAN: 'true' | 'false';
terminal POSITION: 'left' | 'center' | 'right';
terminal LETTER: ('A'..'Z');
terminal ALPHANUMERIC: INT | LETTER;
terminal COLORSTRING: LETTER+ | '#' ALPHANUMERIC+ | 'RGB('INT+','INT+','INT+')';
//terminal CELLREF: ('A'..'Z')('0'..'9');
terminal LINE: 'rightVerticalLine' | 'leftVertical' BOOLEAN;
