grammar org.xtext.example.mydsl.MyDsl with org.eclipse.xtext.common.Terminals

generate myDsl "http://www.xtext.org/example/mydsl/MyDsl"

SystemRoot: tables+=Table+;

Table: 'Table' name=ID nrColumns=NrColumns (columns+=Column)+;

terminal LINE: 'rightVerticalLine' | 'leftVertical' BOOLEAN;
terminal POSITION: 'left' | 'center' | 'right';
terminal LETTER: ('A'..'Z');
terminal ALPHANUMERIC: INT | LETTER;
terminal COLORSTRING: LETTER+ | '#' ALPHANUMERIC+ | 'RGB('INT+','INT+','INT+')';
terminal BOOLEAN: 'true' | 'false';
terminal CELLREF: ('A'..'Z')('0'..'9');

Column: 'Column' letter=LETTER (width=WIDTH)? (alignment=ALIGNMENT)? (color=COLOR)? (line+=LINE)* (cell+=CELL)*;
NrColumns: 'Columns' Nr=INT;
WIDTH: 'Width' number=INT 'cm';
ALIGNMENT: 'Alignment' position=POSITION;
COLOR: 'Color' colorstring=COLORSTRING;
CELL: 'Cell' number=INT color=COLOR? value=VALUE?;

MATH: 'sum' | 'mean' | 'median';
VALUE: 'Value' (string=STRING | expr=Exp | math=MATH '(' range=CELLRANGE ')');

Exp returns Expression:
    Term (
        ({Plus.left=current} '+' right=Term) |
        ({Minus.left=current} '-' right=Term)
    )*;

Term returns Expression:
    Factor (
        ({Mult.left=current} '*' right=Factor) |
        ({Div.left=current} '/' right=Factor)
    )*;

Factor returns Expression:
    {MATHUNIT} (number=INT | cellref=CELLREF) |
    '(' Exp ')';

CELLRANGE: rangestart=CELLREF ':' rangeend=CELLREF;