/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myDsl.ADD;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.SUB;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>ADD</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ADDImpl#getSub1 <em>Sub1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ADDImpl#getSub2 <em>Sub2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ADDImpl extends MinimalEObjectImpl.Container implements ADD
{
  /**
   * The cached value of the '{@link #getSub1() <em>Sub1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSub1()
   * @generated
   * @ordered
   */
  protected SUB sub1;

  /**
   * The cached value of the '{@link #getSub2() <em>Sub2</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSub2()
   * @generated
   * @ordered
   */
  protected EList<SUB> sub2;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ADDImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.ADD;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SUB getSub1()
  {
    return sub1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSub1(SUB newSub1, NotificationChain msgs)
  {
    SUB oldSub1 = sub1;
    sub1 = newSub1;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ADD__SUB1, oldSub1, newSub1);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSub1(SUB newSub1)
  {
    if (newSub1 != sub1)
    {
      NotificationChain msgs = null;
      if (sub1 != null)
        msgs = ((InternalEObject)sub1).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ADD__SUB1, null, msgs);
      if (newSub1 != null)
        msgs = ((InternalEObject)newSub1).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ADD__SUB1, null, msgs);
      msgs = basicSetSub1(newSub1, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ADD__SUB1, newSub1, newSub1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<SUB> getSub2()
  {
    if (sub2 == null)
    {
      sub2 = new EObjectContainmentEList<SUB>(SUB.class, this, MyDslPackage.ADD__SUB2);
    }
    return sub2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.ADD__SUB1:
        return basicSetSub1(null, msgs);
      case MyDslPackage.ADD__SUB2:
        return ((InternalEList<?>)getSub2()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.ADD__SUB1:
        return getSub1();
      case MyDslPackage.ADD__SUB2:
        return getSub2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.ADD__SUB1:
        setSub1((SUB)newValue);
        return;
      case MyDslPackage.ADD__SUB2:
        getSub2().clear();
        getSub2().addAll((Collection<? extends SUB>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ADD__SUB1:
        setSub1((SUB)null);
        return;
      case MyDslPackage.ADD__SUB2:
        getSub2().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ADD__SUB1:
        return sub1 != null;
      case MyDslPackage.ADD__SUB2:
        return sub2 != null && !sub2.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ADDImpl
