/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.CELLRANGE;
import org.xtext.example.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>CELLRANGE</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.CELLRANGEImpl#getRangestart <em>Rangestart</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.CELLRANGEImpl#getRangeend <em>Rangeend</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CELLRANGEImpl extends MinimalEObjectImpl.Container implements CELLRANGE
{
  /**
   * The default value of the '{@link #getRangestart() <em>Rangestart</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRangestart()
   * @generated
   * @ordered
   */
  protected static final String RANGESTART_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRangestart() <em>Rangestart</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRangestart()
   * @generated
   * @ordered
   */
  protected String rangestart = RANGESTART_EDEFAULT;

  /**
   * The default value of the '{@link #getRangeend() <em>Rangeend</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRangeend()
   * @generated
   * @ordered
   */
  protected static final String RANGEEND_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRangeend() <em>Rangeend</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRangeend()
   * @generated
   * @ordered
   */
  protected String rangeend = RANGEEND_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CELLRANGEImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.CELLRANGE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRangestart()
  {
    return rangestart;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRangestart(String newRangestart)
  {
    String oldRangestart = rangestart;
    rangestart = newRangestart;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.CELLRANGE__RANGESTART, oldRangestart, rangestart));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRangeend()
  {
    return rangeend;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRangeend(String newRangeend)
  {
    String oldRangeend = rangeend;
    rangeend = newRangeend;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.CELLRANGE__RANGEEND, oldRangeend, rangeend));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.CELLRANGE__RANGESTART:
        return getRangestart();
      case MyDslPackage.CELLRANGE__RANGEEND:
        return getRangeend();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.CELLRANGE__RANGESTART:
        setRangestart((String)newValue);
        return;
      case MyDslPackage.CELLRANGE__RANGEEND:
        setRangeend((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.CELLRANGE__RANGESTART:
        setRangestart(RANGESTART_EDEFAULT);
        return;
      case MyDslPackage.CELLRANGE__RANGEEND:
        setRangeend(RANGEEND_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.CELLRANGE__RANGESTART:
        return RANGESTART_EDEFAULT == null ? rangestart != null : !RANGESTART_EDEFAULT.equals(rangestart);
      case MyDslPackage.CELLRANGE__RANGEEND:
        return RANGEEND_EDEFAULT == null ? rangeend != null : !RANGEEND_EDEFAULT.equals(rangeend);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (rangestart: ");
    result.append(rangestart);
    result.append(", rangeend: ");
    result.append(rangeend);
    result.append(')');
    return result.toString();
  }

} //CELLRANGEImpl
