/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myDsl.ALIGNMENT;
import org.xtext.example.mydsl.myDsl.CELL;
import org.xtext.example.mydsl.myDsl.COLOR;
import org.xtext.example.mydsl.myDsl.Column;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.WIDTH;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Column</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ColumnImpl#getLetter <em>Letter</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ColumnImpl#getWidth <em>Width</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ColumnImpl#getAlignment <em>Alignment</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ColumnImpl#getColor <em>Color</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ColumnImpl#getLine <em>Line</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ColumnImpl#getCell <em>Cell</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ColumnImpl extends MinimalEObjectImpl.Container implements Column
{
  /**
   * The default value of the '{@link #getLetter() <em>Letter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLetter()
   * @generated
   * @ordered
   */
  protected static final String LETTER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLetter() <em>Letter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLetter()
   * @generated
   * @ordered
   */
  protected String letter = LETTER_EDEFAULT;

  /**
   * The cached value of the '{@link #getWidth() <em>Width</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWidth()
   * @generated
   * @ordered
   */
  protected WIDTH width;

  /**
   * The cached value of the '{@link #getAlignment() <em>Alignment</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAlignment()
   * @generated
   * @ordered
   */
  protected ALIGNMENT alignment;

  /**
   * The cached value of the '{@link #getColor() <em>Color</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColor()
   * @generated
   * @ordered
   */
  protected COLOR color;

  /**
   * The cached value of the '{@link #getLine() <em>Line</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLine()
   * @generated
   * @ordered
   */
  protected EList<String> line;

  /**
   * The cached value of the '{@link #getCell() <em>Cell</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCell()
   * @generated
   * @ordered
   */
  protected EList<CELL> cell;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ColumnImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.COLUMN;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLetter()
  {
    return letter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLetter(String newLetter)
  {
    String oldLetter = letter;
    letter = newLetter;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.COLUMN__LETTER, oldLetter, letter));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public WIDTH getWidth()
  {
    return width;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetWidth(WIDTH newWidth, NotificationChain msgs)
  {
    WIDTH oldWidth = width;
    width = newWidth;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.COLUMN__WIDTH, oldWidth, newWidth);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWidth(WIDTH newWidth)
  {
    if (newWidth != width)
    {
      NotificationChain msgs = null;
      if (width != null)
        msgs = ((InternalEObject)width).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.COLUMN__WIDTH, null, msgs);
      if (newWidth != null)
        msgs = ((InternalEObject)newWidth).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.COLUMN__WIDTH, null, msgs);
      msgs = basicSetWidth(newWidth, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.COLUMN__WIDTH, newWidth, newWidth));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ALIGNMENT getAlignment()
  {
    return alignment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAlignment(ALIGNMENT newAlignment, NotificationChain msgs)
  {
    ALIGNMENT oldAlignment = alignment;
    alignment = newAlignment;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.COLUMN__ALIGNMENT, oldAlignment, newAlignment);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAlignment(ALIGNMENT newAlignment)
  {
    if (newAlignment != alignment)
    {
      NotificationChain msgs = null;
      if (alignment != null)
        msgs = ((InternalEObject)alignment).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.COLUMN__ALIGNMENT, null, msgs);
      if (newAlignment != null)
        msgs = ((InternalEObject)newAlignment).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.COLUMN__ALIGNMENT, null, msgs);
      msgs = basicSetAlignment(newAlignment, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.COLUMN__ALIGNMENT, newAlignment, newAlignment));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public COLOR getColor()
  {
    return color;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetColor(COLOR newColor, NotificationChain msgs)
  {
    COLOR oldColor = color;
    color = newColor;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.COLUMN__COLOR, oldColor, newColor);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setColor(COLOR newColor)
  {
    if (newColor != color)
    {
      NotificationChain msgs = null;
      if (color != null)
        msgs = ((InternalEObject)color).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.COLUMN__COLOR, null, msgs);
      if (newColor != null)
        msgs = ((InternalEObject)newColor).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.COLUMN__COLOR, null, msgs);
      msgs = basicSetColor(newColor, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.COLUMN__COLOR, newColor, newColor));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getLine()
  {
    if (line == null)
    {
      line = new EDataTypeEList<String>(String.class, this, MyDslPackage.COLUMN__LINE);
    }
    return line;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<CELL> getCell()
  {
    if (cell == null)
    {
      cell = new EObjectContainmentEList<CELL>(CELL.class, this, MyDslPackage.COLUMN__CELL);
    }
    return cell;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.COLUMN__WIDTH:
        return basicSetWidth(null, msgs);
      case MyDslPackage.COLUMN__ALIGNMENT:
        return basicSetAlignment(null, msgs);
      case MyDslPackage.COLUMN__COLOR:
        return basicSetColor(null, msgs);
      case MyDslPackage.COLUMN__CELL:
        return ((InternalEList<?>)getCell()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.COLUMN__LETTER:
        return getLetter();
      case MyDslPackage.COLUMN__WIDTH:
        return getWidth();
      case MyDslPackage.COLUMN__ALIGNMENT:
        return getAlignment();
      case MyDslPackage.COLUMN__COLOR:
        return getColor();
      case MyDslPackage.COLUMN__LINE:
        return getLine();
      case MyDslPackage.COLUMN__CELL:
        return getCell();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.COLUMN__LETTER:
        setLetter((String)newValue);
        return;
      case MyDslPackage.COLUMN__WIDTH:
        setWidth((WIDTH)newValue);
        return;
      case MyDslPackage.COLUMN__ALIGNMENT:
        setAlignment((ALIGNMENT)newValue);
        return;
      case MyDslPackage.COLUMN__COLOR:
        setColor((COLOR)newValue);
        return;
      case MyDslPackage.COLUMN__LINE:
        getLine().clear();
        getLine().addAll((Collection<? extends String>)newValue);
        return;
      case MyDslPackage.COLUMN__CELL:
        getCell().clear();
        getCell().addAll((Collection<? extends CELL>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.COLUMN__LETTER:
        setLetter(LETTER_EDEFAULT);
        return;
      case MyDslPackage.COLUMN__WIDTH:
        setWidth((WIDTH)null);
        return;
      case MyDslPackage.COLUMN__ALIGNMENT:
        setAlignment((ALIGNMENT)null);
        return;
      case MyDslPackage.COLUMN__COLOR:
        setColor((COLOR)null);
        return;
      case MyDslPackage.COLUMN__LINE:
        getLine().clear();
        return;
      case MyDslPackage.COLUMN__CELL:
        getCell().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.COLUMN__LETTER:
        return LETTER_EDEFAULT == null ? letter != null : !LETTER_EDEFAULT.equals(letter);
      case MyDslPackage.COLUMN__WIDTH:
        return width != null;
      case MyDslPackage.COLUMN__ALIGNMENT:
        return alignment != null;
      case MyDslPackage.COLUMN__COLOR:
        return color != null;
      case MyDslPackage.COLUMN__LINE:
        return line != null && !line.isEmpty();
      case MyDslPackage.COLUMN__CELL:
        return cell != null && !cell.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (letter: ");
    result.append(letter);
    result.append(", line: ");
    result.append(line);
    result.append(')');
    return result.toString();
  }

} //ColumnImpl
