/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myDsl.DIVID;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.PRIM;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>DIVID</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.DIVIDImpl#getPrim1 <em>Prim1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.DIVIDImpl#getPrim2 <em>Prim2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DIVIDImpl extends MinimalEObjectImpl.Container implements DIVID
{
  /**
   * The cached value of the '{@link #getPrim1() <em>Prim1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrim1()
   * @generated
   * @ordered
   */
  protected PRIM prim1;

  /**
   * The cached value of the '{@link #getPrim2() <em>Prim2</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrim2()
   * @generated
   * @ordered
   */
  protected EList<PRIM> prim2;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DIVIDImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.DIVID;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PRIM getPrim1()
  {
    return prim1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPrim1(PRIM newPrim1, NotificationChain msgs)
  {
    PRIM oldPrim1 = prim1;
    prim1 = newPrim1;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.DIVID__PRIM1, oldPrim1, newPrim1);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPrim1(PRIM newPrim1)
  {
    if (newPrim1 != prim1)
    {
      NotificationChain msgs = null;
      if (prim1 != null)
        msgs = ((InternalEObject)prim1).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.DIVID__PRIM1, null, msgs);
      if (newPrim1 != null)
        msgs = ((InternalEObject)newPrim1).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.DIVID__PRIM1, null, msgs);
      msgs = basicSetPrim1(newPrim1, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.DIVID__PRIM1, newPrim1, newPrim1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<PRIM> getPrim2()
  {
    if (prim2 == null)
    {
      prim2 = new EObjectContainmentEList<PRIM>(PRIM.class, this, MyDslPackage.DIVID__PRIM2);
    }
    return prim2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.DIVID__PRIM1:
        return basicSetPrim1(null, msgs);
      case MyDslPackage.DIVID__PRIM2:
        return ((InternalEList<?>)getPrim2()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.DIVID__PRIM1:
        return getPrim1();
      case MyDslPackage.DIVID__PRIM2:
        return getPrim2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.DIVID__PRIM1:
        setPrim1((PRIM)newValue);
        return;
      case MyDslPackage.DIVID__PRIM2:
        getPrim2().clear();
        getPrim2().addAll((Collection<? extends PRIM>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.DIVID__PRIM1:
        setPrim1((PRIM)null);
        return;
      case MyDslPackage.DIVID__PRIM2:
        getPrim2().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.DIVID__PRIM1:
        return prim1 != null;
      case MyDslPackage.DIVID__PRIM2:
        return prim2 != null && !prim2.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //DIVIDImpl
