/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myDsl.DIVID;
import org.xtext.example.mydsl.myDsl.MULT;
import org.xtext.example.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>MULT</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.MULTImpl#getDivid1 <em>Divid1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.MULTImpl#getDivid2 <em>Divid2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MULTImpl extends MinimalEObjectImpl.Container implements MULT
{
  /**
   * The cached value of the '{@link #getDivid1() <em>Divid1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDivid1()
   * @generated
   * @ordered
   */
  protected DIVID divid1;

  /**
   * The cached value of the '{@link #getDivid2() <em>Divid2</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDivid2()
   * @generated
   * @ordered
   */
  protected EList<DIVID> divid2;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MULTImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.MULT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DIVID getDivid1()
  {
    return divid1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDivid1(DIVID newDivid1, NotificationChain msgs)
  {
    DIVID oldDivid1 = divid1;
    divid1 = newDivid1;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.MULT__DIVID1, oldDivid1, newDivid1);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDivid1(DIVID newDivid1)
  {
    if (newDivid1 != divid1)
    {
      NotificationChain msgs = null;
      if (divid1 != null)
        msgs = ((InternalEObject)divid1).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.MULT__DIVID1, null, msgs);
      if (newDivid1 != null)
        msgs = ((InternalEObject)newDivid1).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.MULT__DIVID1, null, msgs);
      msgs = basicSetDivid1(newDivid1, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.MULT__DIVID1, newDivid1, newDivid1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<DIVID> getDivid2()
  {
    if (divid2 == null)
    {
      divid2 = new EObjectContainmentEList<DIVID>(DIVID.class, this, MyDslPackage.MULT__DIVID2);
    }
    return divid2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.MULT__DIVID1:
        return basicSetDivid1(null, msgs);
      case MyDslPackage.MULT__DIVID2:
        return ((InternalEList<?>)getDivid2()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.MULT__DIVID1:
        return getDivid1();
      case MyDslPackage.MULT__DIVID2:
        return getDivid2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.MULT__DIVID1:
        setDivid1((DIVID)newValue);
        return;
      case MyDslPackage.MULT__DIVID2:
        getDivid2().clear();
        getDivid2().addAll((Collection<? extends DIVID>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.MULT__DIVID1:
        setDivid1((DIVID)null);
        return;
      case MyDslPackage.MULT__DIVID2:
        getDivid2().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.MULT__DIVID1:
        return divid1 != null;
      case MyDslPackage.MULT__DIVID2:
        return divid2 != null && !divid2.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //MULTImpl
