/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.ADD;
import org.xtext.example.mydsl.myDsl.MATHUNIT;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.PRIM;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>PRIM</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.PRIMImpl#getMathunit <em>Mathunit</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.PRIMImpl#getAdd <em>Add</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PRIMImpl extends MinimalEObjectImpl.Container implements PRIM
{
  /**
   * The cached value of the '{@link #getMathunit() <em>Mathunit</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMathunit()
   * @generated
   * @ordered
   */
  protected MATHUNIT mathunit;

  /**
   * The cached value of the '{@link #getAdd() <em>Add</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAdd()
   * @generated
   * @ordered
   */
  protected ADD add;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PRIMImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.PRIM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MATHUNIT getMathunit()
  {
    return mathunit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMathunit(MATHUNIT newMathunit, NotificationChain msgs)
  {
    MATHUNIT oldMathunit = mathunit;
    mathunit = newMathunit;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.PRIM__MATHUNIT, oldMathunit, newMathunit);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMathunit(MATHUNIT newMathunit)
  {
    if (newMathunit != mathunit)
    {
      NotificationChain msgs = null;
      if (mathunit != null)
        msgs = ((InternalEObject)mathunit).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.PRIM__MATHUNIT, null, msgs);
      if (newMathunit != null)
        msgs = ((InternalEObject)newMathunit).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.PRIM__MATHUNIT, null, msgs);
      msgs = basicSetMathunit(newMathunit, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.PRIM__MATHUNIT, newMathunit, newMathunit));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ADD getAdd()
  {
    return add;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAdd(ADD newAdd, NotificationChain msgs)
  {
    ADD oldAdd = add;
    add = newAdd;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.PRIM__ADD, oldAdd, newAdd);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAdd(ADD newAdd)
  {
    if (newAdd != add)
    {
      NotificationChain msgs = null;
      if (add != null)
        msgs = ((InternalEObject)add).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.PRIM__ADD, null, msgs);
      if (newAdd != null)
        msgs = ((InternalEObject)newAdd).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.PRIM__ADD, null, msgs);
      msgs = basicSetAdd(newAdd, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.PRIM__ADD, newAdd, newAdd));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.PRIM__MATHUNIT:
        return basicSetMathunit(null, msgs);
      case MyDslPackage.PRIM__ADD:
        return basicSetAdd(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.PRIM__MATHUNIT:
        return getMathunit();
      case MyDslPackage.PRIM__ADD:
        return getAdd();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.PRIM__MATHUNIT:
        setMathunit((MATHUNIT)newValue);
        return;
      case MyDslPackage.PRIM__ADD:
        setAdd((ADD)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.PRIM__MATHUNIT:
        setMathunit((MATHUNIT)null);
        return;
      case MyDslPackage.PRIM__ADD:
        setAdd((ADD)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.PRIM__MATHUNIT:
        return mathunit != null;
      case MyDslPackage.PRIM__ADD:
        return add != null;
    }
    return super.eIsSet(featureID);
  }

} //PRIMImpl
