/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myDsl.MULT;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.SUB;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>SUB</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.SUBImpl#getMult1 <em>Mult1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.SUBImpl#getMult2 <em>Mult2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SUBImpl extends MinimalEObjectImpl.Container implements SUB
{
  /**
   * The cached value of the '{@link #getMult1() <em>Mult1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMult1()
   * @generated
   * @ordered
   */
  protected MULT mult1;

  /**
   * The cached value of the '{@link #getMult2() <em>Mult2</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMult2()
   * @generated
   * @ordered
   */
  protected EList<MULT> mult2;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SUBImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.SUB;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MULT getMult1()
  {
    return mult1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMult1(MULT newMult1, NotificationChain msgs)
  {
    MULT oldMult1 = mult1;
    mult1 = newMult1;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.SUB__MULT1, oldMult1, newMult1);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMult1(MULT newMult1)
  {
    if (newMult1 != mult1)
    {
      NotificationChain msgs = null;
      if (mult1 != null)
        msgs = ((InternalEObject)mult1).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.SUB__MULT1, null, msgs);
      if (newMult1 != null)
        msgs = ((InternalEObject)newMult1).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.SUB__MULT1, null, msgs);
      msgs = basicSetMult1(newMult1, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.SUB__MULT1, newMult1, newMult1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<MULT> getMult2()
  {
    if (mult2 == null)
    {
      mult2 = new EObjectContainmentEList<MULT>(MULT.class, this, MyDslPackage.SUB__MULT2);
    }
    return mult2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.SUB__MULT1:
        return basicSetMult1(null, msgs);
      case MyDslPackage.SUB__MULT2:
        return ((InternalEList<?>)getMult2()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.SUB__MULT1:
        return getMult1();
      case MyDslPackage.SUB__MULT2:
        return getMult2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.SUB__MULT1:
        setMult1((MULT)newValue);
        return;
      case MyDslPackage.SUB__MULT2:
        getMult2().clear();
        getMult2().addAll((Collection<? extends MULT>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.SUB__MULT1:
        setMult1((MULT)null);
        return;
      case MyDslPackage.SUB__MULT2:
        getMult2().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.SUB__MULT1:
        return mult1 != null;
      case MyDslPackage.SUB__MULT2:
        return mult2 != null && !mult2.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //SUBImpl
