/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.mydsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
