/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getMATHAccess().getAlternatives(), "rule__MATH__Alternatives");
			builder.put(grammarAccess.getVALUEAccess().getAlternatives_1(), "rule__VALUE__Alternatives_1");
			builder.put(grammarAccess.getPRIMAccess().getAlternatives(), "rule__PRIM__Alternatives");
			builder.put(grammarAccess.getMATHUNITAccess().getAlternatives(), "rule__MATHUNIT__Alternatives");
			builder.put(grammarAccess.getTableAccess().getGroup(), "rule__Table__Group__0");
			builder.put(grammarAccess.getColumnAccess().getGroup(), "rule__Column__Group__0");
			builder.put(grammarAccess.getNrColumnsAccess().getGroup(), "rule__NrColumns__Group__0");
			builder.put(grammarAccess.getWIDTHAccess().getGroup(), "rule__WIDTH__Group__0");
			builder.put(grammarAccess.getALIGNMENTAccess().getGroup(), "rule__ALIGNMENT__Group__0");
			builder.put(grammarAccess.getCOLORAccess().getGroup(), "rule__COLOR__Group__0");
			builder.put(grammarAccess.getCELLAccess().getGroup(), "rule__CELL__Group__0");
			builder.put(grammarAccess.getVALUEAccess().getGroup(), "rule__VALUE__Group__0");
			builder.put(grammarAccess.getVALUEAccess().getGroup_1_2(), "rule__VALUE__Group_1_2__0");
			builder.put(grammarAccess.getADDAccess().getGroup(), "rule__ADD__Group__0");
			builder.put(grammarAccess.getADDAccess().getGroup_1(), "rule__ADD__Group_1__0");
			builder.put(grammarAccess.getSUBAccess().getGroup(), "rule__SUB__Group__0");
			builder.put(grammarAccess.getSUBAccess().getGroup_1(), "rule__SUB__Group_1__0");
			builder.put(grammarAccess.getMULTAccess().getGroup(), "rule__MULT__Group__0");
			builder.put(grammarAccess.getMULTAccess().getGroup_1(), "rule__MULT__Group_1__0");
			builder.put(grammarAccess.getDIVIDAccess().getGroup(), "rule__DIVID__Group__0");
			builder.put(grammarAccess.getDIVIDAccess().getGroup_1(), "rule__DIVID__Group_1__0");
			builder.put(grammarAccess.getPRIMAccess().getGroup_1(), "rule__PRIM__Group_1__0");
			builder.put(grammarAccess.getCELLRANGEAccess().getGroup(), "rule__CELLRANGE__Group__0");
			builder.put(grammarAccess.getTableAccess().getNameAssignment_1(), "rule__Table__NameAssignment_1");
			builder.put(grammarAccess.getTableAccess().getNrColumnsAssignment_2(), "rule__Table__NrColumnsAssignment_2");
			builder.put(grammarAccess.getTableAccess().getColumnsAssignment_3(), "rule__Table__ColumnsAssignment_3");
			builder.put(grammarAccess.getColumnAccess().getLetterAssignment_1(), "rule__Column__LetterAssignment_1");
			builder.put(grammarAccess.getColumnAccess().getWidthAssignment_2(), "rule__Column__WidthAssignment_2");
			builder.put(grammarAccess.getColumnAccess().getAlignmentAssignment_3(), "rule__Column__AlignmentAssignment_3");
			builder.put(grammarAccess.getColumnAccess().getColorAssignment_4(), "rule__Column__ColorAssignment_4");
			builder.put(grammarAccess.getColumnAccess().getLineAssignment_5(), "rule__Column__LineAssignment_5");
			builder.put(grammarAccess.getColumnAccess().getCellAssignment_6(), "rule__Column__CellAssignment_6");
			builder.put(grammarAccess.getNrColumnsAccess().getNrAssignment_1(), "rule__NrColumns__NrAssignment_1");
			builder.put(grammarAccess.getWIDTHAccess().getNumberAssignment_1(), "rule__WIDTH__NumberAssignment_1");
			builder.put(grammarAccess.getALIGNMENTAccess().getPositionAssignment_1(), "rule__ALIGNMENT__PositionAssignment_1");
			builder.put(grammarAccess.getCOLORAccess().getColorstringAssignment_1(), "rule__COLOR__ColorstringAssignment_1");
			builder.put(grammarAccess.getCELLAccess().getNumberAssignment_1(), "rule__CELL__NumberAssignment_1");
			builder.put(grammarAccess.getCELLAccess().getColorAssignment_2(), "rule__CELL__ColorAssignment_2");
			builder.put(grammarAccess.getCELLAccess().getValueAssignment_3(), "rule__CELL__ValueAssignment_3");
			builder.put(grammarAccess.getVALUEAccess().getStringAssignment_1_0(), "rule__VALUE__StringAssignment_1_0");
			builder.put(grammarAccess.getVALUEAccess().getExprAssignment_1_1(), "rule__VALUE__ExprAssignment_1_1");
			builder.put(grammarAccess.getVALUEAccess().getMathAssignment_1_2_0(), "rule__VALUE__MathAssignment_1_2_0");
			builder.put(grammarAccess.getVALUEAccess().getRangeAssignment_1_2_1(), "rule__VALUE__RangeAssignment_1_2_1");
			builder.put(grammarAccess.getADDAccess().getSub1Assignment_0(), "rule__ADD__Sub1Assignment_0");
			builder.put(grammarAccess.getADDAccess().getSub2Assignment_1_1(), "rule__ADD__Sub2Assignment_1_1");
			builder.put(grammarAccess.getSUBAccess().getMult1Assignment_0(), "rule__SUB__Mult1Assignment_0");
			builder.put(grammarAccess.getSUBAccess().getMult2Assignment_1_1(), "rule__SUB__Mult2Assignment_1_1");
			builder.put(grammarAccess.getMULTAccess().getDivid1Assignment_0(), "rule__MULT__Divid1Assignment_0");
			builder.put(grammarAccess.getMULTAccess().getDivid2Assignment_1_1(), "rule__MULT__Divid2Assignment_1_1");
			builder.put(grammarAccess.getDIVIDAccess().getPrim1Assignment_0(), "rule__DIVID__Prim1Assignment_0");
			builder.put(grammarAccess.getDIVIDAccess().getPrim2Assignment_1_1(), "rule__DIVID__Prim2Assignment_1_1");
			builder.put(grammarAccess.getPRIMAccess().getMathunitAssignment_0(), "rule__PRIM__MathunitAssignment_0");
			builder.put(grammarAccess.getPRIMAccess().getAddAssignment_1_1(), "rule__PRIM__AddAssignment_1_1");
			builder.put(grammarAccess.getCELLRANGEAccess().getRangestartAssignment_0(), "rule__CELLRANGE__RangestartAssignment_0");
			builder.put(grammarAccess.getCELLRANGEAccess().getRangeendAssignment_2(), "rule__CELLRANGE__RangeendAssignment_2");
			builder.put(grammarAccess.getMATHUNITAccess().getNumberAssignment_0(), "rule__MATHUNIT__NumberAssignment_0");
			builder.put(grammarAccess.getMATHUNITAccess().getCellrefAssignment_1(), "rule__MATHUNIT__CellrefAssignment_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
