/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.mydsl.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.AbstractGenerator
import org.eclipse.xtext.generator.IFileSystemAccess2
import org.eclipse.xtext.generator.IGeneratorContext
import org.xtext.example.mydsl.myDsl.Table
import org.xtext.example.mydsl.myDsl.VALUE
import org.xtext.example.mydsl.myDsl.MATHUNIT
import org.xtext.example.mydsl.myDsl.Expression
import org.xtext.example.mydsl.myDsl.Plus
import org.xtext.example.mydsl.myDsl.Minus
import org.xtext.example.mydsl.myDsl.Mult
import org.xtext.example.mydsl.myDsl.Div
import java.util.ArrayList
import java.util.HashMap

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
class MyDslGenerator extends AbstractGenerator {

    override void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
        val table = resource.allContents
                .filter(Table)
                .findFirst[true];
        val rows = getRowData(table);
        fsa.generateFile('greetings.txt', table.compile(rows));
    }

    private def getCellRef(int int1, int int2) {
        val line = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
        var ref = line.charAt(int1) + int2.toString();
        return ref
    }

    private def ArrayList<ArrayList<String>> getRowData(Table table) {
        // Fase 1: Læg alle unevaluerede celleværdier i et HashMap
        val unevaluatedcellref = new HashMap<String, VALUE>();
        for (var i = 0; i < table.columns.length; i += 1) {
            for (var j = 0; j < table.columns.get(i).cell.length; j += 1) {
                val cellref = getCellRef(i, 1 + j)
                unevaluatedcellref.put(cellref, table.columns.get(i).cell.get(j).value);
            }
        }

        // Fase 2: Evaluer alle celleværdier
        val outerArrayList = new ArrayList<ArrayList<String>>()
        for (var i = 0; i < table.columns.length; i += 1) {
            val row = new ArrayList<String>();
            for (var j = 0; j < table.columns.get(i).cell.length; j += 1) {
                row.add(table.columns.get(i).cell.get(j).value.cellValueEvaluator(unevaluatedcellref));
            }
            outerArrayList.add(row);
        }
        return this.transpose(outerArrayList);
    }

    private def String compile(Table table, ArrayList<ArrayList<String>> rows) {
        return '''
        \begin{tabular}{ |«FOR col : table.columns»c|«ENDFOR» }
        «FOR row: rows»
        \hline
            «FOR cell : row SEPARATOR ' & '»«cell»«ENDFOR» \\
        «ENDFOR»
        \hline
        \end{tabular}
       ''';
    }

    private def String cellValueEvaluator(VALUE value, HashMap<String, VALUE> valueMap) {
        if (value.string !== null) {
            return value.string
        } else {
            return value.expr.compileExp().toString()
        }
    }

    // Erstatter de 5 gamle metoder (addEval, subEval, multEval, dividEval, primEval, mathunitEval)
    // Matcher den nuværende grammar med Plus/Minus/Mult/Div/MATHUNIT (Left Recursion-fix)
    def float compileExp(Expression exp) {
        switch exp {
            Plus:     exp.left.compileExp() + exp.right.compileExp()
            Minus:    exp.left.compileExp() - exp.right.compileExp()
            Mult:     exp.left.compileExp() * exp.right.compileExp()
            Div:      exp.left.compileExp() / exp.right.compileExp()
            MATHUNIT: if (exp.varRef !== null) {
            			  val varDecl = exp.varRef
            			  return compileExp(varDecl.value.numVal)
                          // Name Resolution: slår cellereference op i HashMap
                          //valueMap.get(exp.cellRef).expr.compileExp(valueMap)
                      } else if (exp.cellRef !== null) {
                          exp.cellRef.value.expr.compileExp()
                      } else {
                          Float.parseFloat(exp.number);
                      }
            default: 0.0f
        }
    }

    private def ArrayList<ArrayList<String>> transpose(ArrayList<ArrayList<String>> matrixIn) {
        // FROM: https://stackoverflow.com/a/28057878
        var matrixOut = new ArrayList<ArrayList<String>>();
        if (!matrixIn.isEmpty()) {
            var noOfElementsInList = matrixIn.get(0).size();
            for (var i = 0; i < noOfElementsInList; i++) {
                var col = new ArrayList<String>();
                for (ArrayList<String> row : matrixIn) {
                    col.add(row.get(i));
                }
                matrixOut.add(col);
            }
        }
        return matrixOut;
    }
}