/*
 * generated by Xtext 2.42.0
 */
package org.example.domainmodel.ide;


/**
 * Use this class to register ide components.
 */
public class DomainModelIdeModule extends AbstractDomainModelIdeModule {
}
