/*
 * generated by Xtext 2.42.0
 */
package org.example.domainmodel.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.example.domainmodel.DomainModelRuntimeModule;
import org.example.domainmodel.DomainModelStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DomainModelIdeSetup extends DomainModelStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DomainModelRuntimeModule(), new DomainModelIdeModule()));
	}
	
}
