/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ADD</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ADD#getSub1 <em>Sub1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ADD#getSub2 <em>Sub2</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getADD()
 * @model
 * @generated
 */
public interface ADD extends EObject
{
  /**
   * Returns the value of the '<em><b>Sub1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sub1</em>' containment reference.
   * @see #setSub1(SUB)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getADD_Sub1()
   * @model containment="true"
   * @generated
   */
  SUB getSub1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ADD#getSub1 <em>Sub1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sub1</em>' containment reference.
   * @see #getSub1()
   * @generated
   */
  void setSub1(SUB value);

  /**
   * Returns the value of the '<em><b>Sub2</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.SUB}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sub2</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getADD_Sub2()
   * @model containment="true"
   * @generated
   */
  EList<SUB> getSub2();

} // ADD
