/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>CELLRANGE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.CELLRANGE#getRangestart <em>Rangestart</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.CELLRANGE#getRangeend <em>Rangeend</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCELLRANGE()
 * @model
 * @generated
 */
public interface CELLRANGE extends EObject
{
  /**
   * Returns the value of the '<em><b>Rangestart</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rangestart</em>' attribute.
   * @see #setRangestart(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCELLRANGE_Rangestart()
   * @model
   * @generated
   */
  String getRangestart();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.CELLRANGE#getRangestart <em>Rangestart</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rangestart</em>' attribute.
   * @see #getRangestart()
   * @generated
   */
  void setRangestart(String value);

  /**
   * Returns the value of the '<em><b>Rangeend</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rangeend</em>' attribute.
   * @see #setRangeend(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCELLRANGE_Rangeend()
   * @model
   * @generated
   */
  String getRangeend();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.CELLRANGE#getRangeend <em>Rangeend</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rangeend</em>' attribute.
   * @see #getRangeend()
   * @generated
   */
  void setRangeend(String value);

} // CELLRANGE
