/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>COLOR</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.COLOR#getColorstring <em>Colorstring</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCOLOR()
 * @model
 * @generated
 */
public interface COLOR extends EObject
{
  /**
   * Returns the value of the '<em><b>Colorstring</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Colorstring</em>' attribute.
   * @see #setColorstring(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCOLOR_Colorstring()
   * @model
   * @generated
   */
  String getColorstring();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.COLOR#getColorstring <em>Colorstring</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Colorstring</em>' attribute.
   * @see #getColorstring()
   * @generated
   */
  void setColorstring(String value);

} // COLOR
