/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Column</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Column#getLetter <em>Letter</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Column#getWidth <em>Width</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Column#getAlignment <em>Alignment</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Column#getColor <em>Color</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Column#getLine <em>Line</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Column#getCell <em>Cell</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getColumn()
 * @model
 * @generated
 */
public interface Column extends EObject
{
  /**
   * Returns the value of the '<em><b>Letter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Letter</em>' attribute.
   * @see #setLetter(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getColumn_Letter()
   * @model
   * @generated
   */
  String getLetter();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Column#getLetter <em>Letter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Letter</em>' attribute.
   * @see #getLetter()
   * @generated
   */
  void setLetter(String value);

  /**
   * Returns the value of the '<em><b>Width</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Width</em>' containment reference.
   * @see #setWidth(WIDTH)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getColumn_Width()
   * @model containment="true"
   * @generated
   */
  WIDTH getWidth();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Column#getWidth <em>Width</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Width</em>' containment reference.
   * @see #getWidth()
   * @generated
   */
  void setWidth(WIDTH value);

  /**
   * Returns the value of the '<em><b>Alignment</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alignment</em>' containment reference.
   * @see #setAlignment(ALIGNMENT)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getColumn_Alignment()
   * @model containment="true"
   * @generated
   */
  ALIGNMENT getAlignment();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Column#getAlignment <em>Alignment</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alignment</em>' containment reference.
   * @see #getAlignment()
   * @generated
   */
  void setAlignment(ALIGNMENT value);

  /**
   * Returns the value of the '<em><b>Color</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Color</em>' containment reference.
   * @see #setColor(COLOR)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getColumn_Color()
   * @model containment="true"
   * @generated
   */
  COLOR getColor();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Column#getColor <em>Color</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Color</em>' containment reference.
   * @see #getColor()
   * @generated
   */
  void setColor(COLOR value);

  /**
   * Returns the value of the '<em><b>Line</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Line</em>' attribute list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getColumn_Line()
   * @model unique="false"
   * @generated
   */
  EList<String> getLine();

  /**
   * Returns the value of the '<em><b>Cell</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.CELL}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cell</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getColumn_Cell()
   * @model containment="true"
   * @generated
   */
  EList<CELL> getCell();

} // Column
