/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DIVID</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.DIVID#getPrim1 <em>Prim1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.DIVID#getPrim2 <em>Prim2</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDIVID()
 * @model
 * @generated
 */
public interface DIVID extends EObject
{
  /**
   * Returns the value of the '<em><b>Prim1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prim1</em>' containment reference.
   * @see #setPrim1(PRIM)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDIVID_Prim1()
   * @model containment="true"
   * @generated
   */
  PRIM getPrim1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.DIVID#getPrim1 <em>Prim1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prim1</em>' containment reference.
   * @see #getPrim1()
   * @generated
   */
  void setPrim1(PRIM value);

  /**
   * Returns the value of the '<em><b>Prim2</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.PRIM}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prim2</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDIVID_Prim2()
   * @model containment="true"
   * @generated
   */
  EList<PRIM> getPrim2();

} // DIVID
