/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>MATHUNIT</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.MATHUNIT#getNumber <em>Number</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.MATHUNIT#getCellref <em>Cellref</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getMATHUNIT()
 * @model
 * @generated
 */
public interface MATHUNIT extends EObject
{
  /**
   * Returns the value of the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number</em>' attribute.
   * @see #setNumber(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getMATHUNIT_Number()
   * @model
   * @generated
   */
  int getNumber();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.MATHUNIT#getNumber <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number</em>' attribute.
   * @see #getNumber()
   * @generated
   */
  void setNumber(int value);

  /**
   * Returns the value of the '<em><b>Cellref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cellref</em>' attribute.
   * @see #setCellref(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getMATHUNIT_Cellref()
   * @model
   * @generated
   */
  String getCellref();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.MATHUNIT#getCellref <em>Cellref</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cellref</em>' attribute.
   * @see #getCellref()
   * @generated
   */
  void setCellref(String value);

} // MATHUNIT
