/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>MULT</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.MULT#getDivid1 <em>Divid1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.MULT#getDivid2 <em>Divid2</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getMULT()
 * @model
 * @generated
 */
public interface MULT extends EObject
{
  /**
   * Returns the value of the '<em><b>Divid1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Divid1</em>' containment reference.
   * @see #setDivid1(DIVID)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getMULT_Divid1()
   * @model containment="true"
   * @generated
   */
  DIVID getDivid1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.MULT#getDivid1 <em>Divid1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Divid1</em>' containment reference.
   * @see #getDivid1()
   * @generated
   */
  void setDivid1(DIVID value);

  /**
   * Returns the value of the '<em><b>Divid2</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.DIVID}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Divid2</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getMULT_Divid2()
   * @model containment="true"
   * @generated
   */
  EList<DIVID> getDivid2();

} // MULT
