/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.TableImpl <em>Table</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.TableImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTable()
   * @generated
   */
  int TABLE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE__NAME = 0;

  /**
   * The feature id for the '<em><b>Nr Columns</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE__NR_COLUMNS = 1;

  /**
   * The feature id for the '<em><b>Columns</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE__COLUMNS = 2;

  /**
   * The number of structural features of the '<em>Table</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ColumnImpl <em>Column</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ColumnImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getColumn()
   * @generated
   */
  int COLUMN = 1;

  /**
   * The feature id for the '<em><b>Letter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN__LETTER = 0;

  /**
   * The feature id for the '<em><b>Width</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN__WIDTH = 1;

  /**
   * The feature id for the '<em><b>Alignment</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN__ALIGNMENT = 2;

  /**
   * The feature id for the '<em><b>Color</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN__COLOR = 3;

  /**
   * The feature id for the '<em><b>Line</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN__LINE = 4;

  /**
   * The feature id for the '<em><b>Cell</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN__CELL = 5;

  /**
   * The number of structural features of the '<em>Column</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.NrColumnsImpl <em>Nr Columns</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.NrColumnsImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNrColumns()
   * @generated
   */
  int NR_COLUMNS = 2;

  /**
   * The feature id for the '<em><b>Nr</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NR_COLUMNS__NR = 0;

  /**
   * The number of structural features of the '<em>Nr Columns</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NR_COLUMNS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.WIDTHImpl <em>WIDTH</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.WIDTHImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getWIDTH()
   * @generated
   */
  int WIDTH = 3;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WIDTH__NUMBER = 0;

  /**
   * The number of structural features of the '<em>WIDTH</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WIDTH_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ALIGNMENTImpl <em>ALIGNMENT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ALIGNMENTImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getALIGNMENT()
   * @generated
   */
  int ALIGNMENT = 4;

  /**
   * The feature id for the '<em><b>Position</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALIGNMENT__POSITION = 0;

  /**
   * The number of structural features of the '<em>ALIGNMENT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALIGNMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.COLORImpl <em>COLOR</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.COLORImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCOLOR()
   * @generated
   */
  int COLOR = 5;

  /**
   * The feature id for the '<em><b>Colorstring</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR__COLORSTRING = 0;

  /**
   * The number of structural features of the '<em>COLOR</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.CELLImpl <em>CELL</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.CELLImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCELL()
   * @generated
   */
  int CELL = 6;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL__NUMBER = 0;

  /**
   * The feature id for the '<em><b>Color</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL__COLOR = 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL__VALUE = 2;

  /**
   * The number of structural features of the '<em>CELL</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.VALUEImpl <em>VALUE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.VALUEImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVALUE()
   * @generated
   */
  int VALUE = 7;

  /**
   * The feature id for the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE__STRING = 0;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE__EXPR = 1;

  /**
   * The feature id for the '<em><b>Math</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE__MATH = 2;

  /**
   * The feature id for the '<em><b>Range</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE__RANGE = 3;

  /**
   * The number of structural features of the '<em>VALUE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ADDImpl <em>ADD</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ADDImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getADD()
   * @generated
   */
  int ADD = 8;

  /**
   * The feature id for the '<em><b>Sub1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD__SUB1 = 0;

  /**
   * The feature id for the '<em><b>Sub2</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD__SUB2 = 1;

  /**
   * The number of structural features of the '<em>ADD</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SUBImpl <em>SUB</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SUBImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSUB()
   * @generated
   */
  int SUB = 9;

  /**
   * The feature id for the '<em><b>Mult1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB__MULT1 = 0;

  /**
   * The feature id for the '<em><b>Mult2</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB__MULT2 = 1;

  /**
   * The number of structural features of the '<em>SUB</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.MULTImpl <em>MULT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.MULTImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getMULT()
   * @generated
   */
  int MULT = 10;

  /**
   * The feature id for the '<em><b>Divid1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT__DIVID1 = 0;

  /**
   * The feature id for the '<em><b>Divid2</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT__DIVID2 = 1;

  /**
   * The number of structural features of the '<em>MULT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.DIVIDImpl <em>DIVID</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.DIVIDImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDIVID()
   * @generated
   */
  int DIVID = 11;

  /**
   * The feature id for the '<em><b>Prim1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVID__PRIM1 = 0;

  /**
   * The feature id for the '<em><b>Prim2</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVID__PRIM2 = 1;

  /**
   * The number of structural features of the '<em>DIVID</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVID_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.PRIMImpl <em>PRIM</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.PRIMImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getPRIM()
   * @generated
   */
  int PRIM = 12;

  /**
   * The feature id for the '<em><b>Mathunit</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIM__MATHUNIT = 0;

  /**
   * The feature id for the '<em><b>Add</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIM__ADD = 1;

  /**
   * The number of structural features of the '<em>PRIM</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.CELLRANGEImpl <em>CELLRANGE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.CELLRANGEImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCELLRANGE()
   * @generated
   */
  int CELLRANGE = 13;

  /**
   * The feature id for the '<em><b>Rangestart</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELLRANGE__RANGESTART = 0;

  /**
   * The feature id for the '<em><b>Rangeend</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELLRANGE__RANGEEND = 1;

  /**
   * The number of structural features of the '<em>CELLRANGE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELLRANGE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.MATHUNITImpl <em>MATHUNIT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.MATHUNITImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getMATHUNIT()
   * @generated
   */
  int MATHUNIT = 14;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATHUNIT__NUMBER = 0;

  /**
   * The feature id for the '<em><b>Cellref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATHUNIT__CELLREF = 1;

  /**
   * The number of structural features of the '<em>MATHUNIT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATHUNIT_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Table <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table</em>'.
   * @see org.xtext.example.mydsl.myDsl.Table
   * @generated
   */
  EClass getTable();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Table#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Table#getName()
   * @see #getTable()
   * @generated
   */
  EAttribute getTable_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Table#getNrColumns <em>Nr Columns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Nr Columns</em>'.
   * @see org.xtext.example.mydsl.myDsl.Table#getNrColumns()
   * @see #getTable()
   * @generated
   */
  EReference getTable_NrColumns();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Table#getColumns <em>Columns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Columns</em>'.
   * @see org.xtext.example.mydsl.myDsl.Table#getColumns()
   * @see #getTable()
   * @generated
   */
  EReference getTable_Columns();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Column <em>Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Column</em>'.
   * @see org.xtext.example.mydsl.myDsl.Column
   * @generated
   */
  EClass getColumn();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Column#getLetter <em>Letter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Letter</em>'.
   * @see org.xtext.example.mydsl.myDsl.Column#getLetter()
   * @see #getColumn()
   * @generated
   */
  EAttribute getColumn_Letter();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Column#getWidth <em>Width</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Width</em>'.
   * @see org.xtext.example.mydsl.myDsl.Column#getWidth()
   * @see #getColumn()
   * @generated
   */
  EReference getColumn_Width();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Column#getAlignment <em>Alignment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Alignment</em>'.
   * @see org.xtext.example.mydsl.myDsl.Column#getAlignment()
   * @see #getColumn()
   * @generated
   */
  EReference getColumn_Alignment();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Column#getColor <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Color</em>'.
   * @see org.xtext.example.mydsl.myDsl.Column#getColor()
   * @see #getColumn()
   * @generated
   */
  EReference getColumn_Color();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.myDsl.Column#getLine <em>Line</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Line</em>'.
   * @see org.xtext.example.mydsl.myDsl.Column#getLine()
   * @see #getColumn()
   * @generated
   */
  EAttribute getColumn_Line();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Column#getCell <em>Cell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cell</em>'.
   * @see org.xtext.example.mydsl.myDsl.Column#getCell()
   * @see #getColumn()
   * @generated
   */
  EReference getColumn_Cell();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.NrColumns <em>Nr Columns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nr Columns</em>'.
   * @see org.xtext.example.mydsl.myDsl.NrColumns
   * @generated
   */
  EClass getNrColumns();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.myDsl.NrColumns#getNr <em>Nr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Nr</em>'.
   * @see org.xtext.example.mydsl.myDsl.NrColumns#getNr()
   * @see #getNrColumns()
   * @generated
   */
  EAttribute getNrColumns_Nr();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.WIDTH <em>WIDTH</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>WIDTH</em>'.
   * @see org.xtext.example.mydsl.myDsl.WIDTH
   * @generated
   */
  EClass getWIDTH();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.WIDTH#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see org.xtext.example.mydsl.myDsl.WIDTH#getNumber()
   * @see #getWIDTH()
   * @generated
   */
  EAttribute getWIDTH_Number();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ALIGNMENT <em>ALIGNMENT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ALIGNMENT</em>'.
   * @see org.xtext.example.mydsl.myDsl.ALIGNMENT
   * @generated
   */
  EClass getALIGNMENT();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ALIGNMENT#getPosition <em>Position</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Position</em>'.
   * @see org.xtext.example.mydsl.myDsl.ALIGNMENT#getPosition()
   * @see #getALIGNMENT()
   * @generated
   */
  EAttribute getALIGNMENT_Position();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.COLOR <em>COLOR</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>COLOR</em>'.
   * @see org.xtext.example.mydsl.myDsl.COLOR
   * @generated
   */
  EClass getCOLOR();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.COLOR#getColorstring <em>Colorstring</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Colorstring</em>'.
   * @see org.xtext.example.mydsl.myDsl.COLOR#getColorstring()
   * @see #getCOLOR()
   * @generated
   */
  EAttribute getCOLOR_Colorstring();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.CELL <em>CELL</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CELL</em>'.
   * @see org.xtext.example.mydsl.myDsl.CELL
   * @generated
   */
  EClass getCELL();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.CELL#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see org.xtext.example.mydsl.myDsl.CELL#getNumber()
   * @see #getCELL()
   * @generated
   */
  EAttribute getCELL_Number();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.CELL#getColor <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Color</em>'.
   * @see org.xtext.example.mydsl.myDsl.CELL#getColor()
   * @see #getCELL()
   * @generated
   */
  EReference getCELL_Color();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.CELL#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.mydsl.myDsl.CELL#getValue()
   * @see #getCELL()
   * @generated
   */
  EReference getCELL_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.VALUE <em>VALUE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>VALUE</em>'.
   * @see org.xtext.example.mydsl.myDsl.VALUE
   * @generated
   */
  EClass getVALUE();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.VALUE#getString <em>String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>String</em>'.
   * @see org.xtext.example.mydsl.myDsl.VALUE#getString()
   * @see #getVALUE()
   * @generated
   */
  EAttribute getVALUE_String();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.VALUE#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see org.xtext.example.mydsl.myDsl.VALUE#getExpr()
   * @see #getVALUE()
   * @generated
   */
  EReference getVALUE_Expr();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.VALUE#getMath <em>Math</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Math</em>'.
   * @see org.xtext.example.mydsl.myDsl.VALUE#getMath()
   * @see #getVALUE()
   * @generated
   */
  EAttribute getVALUE_Math();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.VALUE#getRange <em>Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Range</em>'.
   * @see org.xtext.example.mydsl.myDsl.VALUE#getRange()
   * @see #getVALUE()
   * @generated
   */
  EReference getVALUE_Range();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ADD <em>ADD</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ADD</em>'.
   * @see org.xtext.example.mydsl.myDsl.ADD
   * @generated
   */
  EClass getADD();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ADD#getSub1 <em>Sub1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sub1</em>'.
   * @see org.xtext.example.mydsl.myDsl.ADD#getSub1()
   * @see #getADD()
   * @generated
   */
  EReference getADD_Sub1();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.ADD#getSub2 <em>Sub2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sub2</em>'.
   * @see org.xtext.example.mydsl.myDsl.ADD#getSub2()
   * @see #getADD()
   * @generated
   */
  EReference getADD_Sub2();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.SUB <em>SUB</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SUB</em>'.
   * @see org.xtext.example.mydsl.myDsl.SUB
   * @generated
   */
  EClass getSUB();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.SUB#getMult1 <em>Mult1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Mult1</em>'.
   * @see org.xtext.example.mydsl.myDsl.SUB#getMult1()
   * @see #getSUB()
   * @generated
   */
  EReference getSUB_Mult1();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.SUB#getMult2 <em>Mult2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Mult2</em>'.
   * @see org.xtext.example.mydsl.myDsl.SUB#getMult2()
   * @see #getSUB()
   * @generated
   */
  EReference getSUB_Mult2();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.MULT <em>MULT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MULT</em>'.
   * @see org.xtext.example.mydsl.myDsl.MULT
   * @generated
   */
  EClass getMULT();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.MULT#getDivid1 <em>Divid1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Divid1</em>'.
   * @see org.xtext.example.mydsl.myDsl.MULT#getDivid1()
   * @see #getMULT()
   * @generated
   */
  EReference getMULT_Divid1();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.MULT#getDivid2 <em>Divid2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Divid2</em>'.
   * @see org.xtext.example.mydsl.myDsl.MULT#getDivid2()
   * @see #getMULT()
   * @generated
   */
  EReference getMULT_Divid2();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.DIVID <em>DIVID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>DIVID</em>'.
   * @see org.xtext.example.mydsl.myDsl.DIVID
   * @generated
   */
  EClass getDIVID();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.DIVID#getPrim1 <em>Prim1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Prim1</em>'.
   * @see org.xtext.example.mydsl.myDsl.DIVID#getPrim1()
   * @see #getDIVID()
   * @generated
   */
  EReference getDIVID_Prim1();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.DIVID#getPrim2 <em>Prim2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Prim2</em>'.
   * @see org.xtext.example.mydsl.myDsl.DIVID#getPrim2()
   * @see #getDIVID()
   * @generated
   */
  EReference getDIVID_Prim2();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.PRIM <em>PRIM</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>PRIM</em>'.
   * @see org.xtext.example.mydsl.myDsl.PRIM
   * @generated
   */
  EClass getPRIM();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.PRIM#getMathunit <em>Mathunit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Mathunit</em>'.
   * @see org.xtext.example.mydsl.myDsl.PRIM#getMathunit()
   * @see #getPRIM()
   * @generated
   */
  EReference getPRIM_Mathunit();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.PRIM#getAdd <em>Add</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Add</em>'.
   * @see org.xtext.example.mydsl.myDsl.PRIM#getAdd()
   * @see #getPRIM()
   * @generated
   */
  EReference getPRIM_Add();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.CELLRANGE <em>CELLRANGE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CELLRANGE</em>'.
   * @see org.xtext.example.mydsl.myDsl.CELLRANGE
   * @generated
   */
  EClass getCELLRANGE();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.CELLRANGE#getRangestart <em>Rangestart</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rangestart</em>'.
   * @see org.xtext.example.mydsl.myDsl.CELLRANGE#getRangestart()
   * @see #getCELLRANGE()
   * @generated
   */
  EAttribute getCELLRANGE_Rangestart();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.CELLRANGE#getRangeend <em>Rangeend</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rangeend</em>'.
   * @see org.xtext.example.mydsl.myDsl.CELLRANGE#getRangeend()
   * @see #getCELLRANGE()
   * @generated
   */
  EAttribute getCELLRANGE_Rangeend();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.MATHUNIT <em>MATHUNIT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MATHUNIT</em>'.
   * @see org.xtext.example.mydsl.myDsl.MATHUNIT
   * @generated
   */
  EClass getMATHUNIT();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.MATHUNIT#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see org.xtext.example.mydsl.myDsl.MATHUNIT#getNumber()
   * @see #getMATHUNIT()
   * @generated
   */
  EAttribute getMATHUNIT_Number();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.MATHUNIT#getCellref <em>Cellref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cellref</em>'.
   * @see org.xtext.example.mydsl.myDsl.MATHUNIT#getCellref()
   * @see #getMATHUNIT()
   * @generated
   */
  EAttribute getMATHUNIT_Cellref();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.TableImpl <em>Table</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.TableImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTable()
     * @generated
     */
    EClass TABLE = eINSTANCE.getTable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TABLE__NAME = eINSTANCE.getTable_Name();

    /**
     * The meta object literal for the '<em><b>Nr Columns</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLE__NR_COLUMNS = eINSTANCE.getTable_NrColumns();

    /**
     * The meta object literal for the '<em><b>Columns</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLE__COLUMNS = eINSTANCE.getTable_Columns();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ColumnImpl <em>Column</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ColumnImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getColumn()
     * @generated
     */
    EClass COLUMN = eINSTANCE.getColumn();

    /**
     * The meta object literal for the '<em><b>Letter</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLUMN__LETTER = eINSTANCE.getColumn_Letter();

    /**
     * The meta object literal for the '<em><b>Width</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLUMN__WIDTH = eINSTANCE.getColumn_Width();

    /**
     * The meta object literal for the '<em><b>Alignment</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLUMN__ALIGNMENT = eINSTANCE.getColumn_Alignment();

    /**
     * The meta object literal for the '<em><b>Color</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLUMN__COLOR = eINSTANCE.getColumn_Color();

    /**
     * The meta object literal for the '<em><b>Line</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLUMN__LINE = eINSTANCE.getColumn_Line();

    /**
     * The meta object literal for the '<em><b>Cell</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLUMN__CELL = eINSTANCE.getColumn_Cell();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.NrColumnsImpl <em>Nr Columns</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.NrColumnsImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNrColumns()
     * @generated
     */
    EClass NR_COLUMNS = eINSTANCE.getNrColumns();

    /**
     * The meta object literal for the '<em><b>Nr</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NR_COLUMNS__NR = eINSTANCE.getNrColumns_Nr();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.WIDTHImpl <em>WIDTH</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.WIDTHImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getWIDTH()
     * @generated
     */
    EClass WIDTH = eINSTANCE.getWIDTH();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WIDTH__NUMBER = eINSTANCE.getWIDTH_Number();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ALIGNMENTImpl <em>ALIGNMENT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ALIGNMENTImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getALIGNMENT()
     * @generated
     */
    EClass ALIGNMENT = eINSTANCE.getALIGNMENT();

    /**
     * The meta object literal for the '<em><b>Position</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALIGNMENT__POSITION = eINSTANCE.getALIGNMENT_Position();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.COLORImpl <em>COLOR</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.COLORImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCOLOR()
     * @generated
     */
    EClass COLOR = eINSTANCE.getCOLOR();

    /**
     * The meta object literal for the '<em><b>Colorstring</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLOR__COLORSTRING = eINSTANCE.getCOLOR_Colorstring();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.CELLImpl <em>CELL</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.CELLImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCELL()
     * @generated
     */
    EClass CELL = eINSTANCE.getCELL();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CELL__NUMBER = eINSTANCE.getCELL_Number();

    /**
     * The meta object literal for the '<em><b>Color</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CELL__COLOR = eINSTANCE.getCELL_Color();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CELL__VALUE = eINSTANCE.getCELL_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.VALUEImpl <em>VALUE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.VALUEImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVALUE()
     * @generated
     */
    EClass VALUE = eINSTANCE.getVALUE();

    /**
     * The meta object literal for the '<em><b>String</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALUE__STRING = eINSTANCE.getVALUE_String();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VALUE__EXPR = eINSTANCE.getVALUE_Expr();

    /**
     * The meta object literal for the '<em><b>Math</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALUE__MATH = eINSTANCE.getVALUE_Math();

    /**
     * The meta object literal for the '<em><b>Range</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VALUE__RANGE = eINSTANCE.getVALUE_Range();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ADDImpl <em>ADD</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ADDImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getADD()
     * @generated
     */
    EClass ADD = eINSTANCE.getADD();

    /**
     * The meta object literal for the '<em><b>Sub1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADD__SUB1 = eINSTANCE.getADD_Sub1();

    /**
     * The meta object literal for the '<em><b>Sub2</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADD__SUB2 = eINSTANCE.getADD_Sub2();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SUBImpl <em>SUB</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SUBImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSUB()
     * @generated
     */
    EClass SUB = eINSTANCE.getSUB();

    /**
     * The meta object literal for the '<em><b>Mult1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUB__MULT1 = eINSTANCE.getSUB_Mult1();

    /**
     * The meta object literal for the '<em><b>Mult2</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUB__MULT2 = eINSTANCE.getSUB_Mult2();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.MULTImpl <em>MULT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.MULTImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getMULT()
     * @generated
     */
    EClass MULT = eINSTANCE.getMULT();

    /**
     * The meta object literal for the '<em><b>Divid1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULT__DIVID1 = eINSTANCE.getMULT_Divid1();

    /**
     * The meta object literal for the '<em><b>Divid2</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULT__DIVID2 = eINSTANCE.getMULT_Divid2();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.DIVIDImpl <em>DIVID</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.DIVIDImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDIVID()
     * @generated
     */
    EClass DIVID = eINSTANCE.getDIVID();

    /**
     * The meta object literal for the '<em><b>Prim1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIVID__PRIM1 = eINSTANCE.getDIVID_Prim1();

    /**
     * The meta object literal for the '<em><b>Prim2</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIVID__PRIM2 = eINSTANCE.getDIVID_Prim2();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.PRIMImpl <em>PRIM</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.PRIMImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getPRIM()
     * @generated
     */
    EClass PRIM = eINSTANCE.getPRIM();

    /**
     * The meta object literal for the '<em><b>Mathunit</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRIM__MATHUNIT = eINSTANCE.getPRIM_Mathunit();

    /**
     * The meta object literal for the '<em><b>Add</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRIM__ADD = eINSTANCE.getPRIM_Add();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.CELLRANGEImpl <em>CELLRANGE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.CELLRANGEImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCELLRANGE()
     * @generated
     */
    EClass CELLRANGE = eINSTANCE.getCELLRANGE();

    /**
     * The meta object literal for the '<em><b>Rangestart</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CELLRANGE__RANGESTART = eINSTANCE.getCELLRANGE_Rangestart();

    /**
     * The meta object literal for the '<em><b>Rangeend</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CELLRANGE__RANGEEND = eINSTANCE.getCELLRANGE_Rangeend();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.MATHUNITImpl <em>MATHUNIT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.MATHUNITImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getMATHUNIT()
     * @generated
     */
    EClass MATHUNIT = eINSTANCE.getMATHUNIT();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MATHUNIT__NUMBER = eINSTANCE.getMATHUNIT_Number();

    /**
     * The meta object literal for the '<em><b>Cellref</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MATHUNIT__CELLREF = eINSTANCE.getMATHUNIT_Cellref();

  }

} //MyDslPackage
