/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage
 * @generated
 */
public interface MyDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslFactory eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Table</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Table</em>'.
   * @generated
   */
  Table createTable();

  /**
   * Returns a new object of class '<em>Column</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Column</em>'.
   * @generated
   */
  Column createColumn();

  /**
   * Returns a new object of class '<em>Nr Columns</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Nr Columns</em>'.
   * @generated
   */
  NrColumns createNrColumns();

  /**
   * Returns a new object of class '<em>WIDTH</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>WIDTH</em>'.
   * @generated
   */
  WIDTH createWIDTH();

  /**
   * Returns a new object of class '<em>ALIGNMENT</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ALIGNMENT</em>'.
   * @generated
   */
  ALIGNMENT createALIGNMENT();

  /**
   * Returns a new object of class '<em>COLOR</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>COLOR</em>'.
   * @generated
   */
  COLOR createCOLOR();

  /**
   * Returns a new object of class '<em>CELL</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CELL</em>'.
   * @generated
   */
  CELL createCELL();

  /**
   * Returns a new object of class '<em>VALUE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>VALUE</em>'.
   * @generated
   */
  VALUE createVALUE();

  /**
   * Returns a new object of class '<em>ADD</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ADD</em>'.
   * @generated
   */
  ADD createADD();

  /**
   * Returns a new object of class '<em>SUB</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SUB</em>'.
   * @generated
   */
  SUB createSUB();

  /**
   * Returns a new object of class '<em>MULT</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MULT</em>'.
   * @generated
   */
  MULT createMULT();

  /**
   * Returns a new object of class '<em>DIVID</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DIVID</em>'.
   * @generated
   */
  DIVID createDIVID();

  /**
   * Returns a new object of class '<em>PRIM</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PRIM</em>'.
   * @generated
   */
  PRIM createPRIM();

  /**
   * Returns a new object of class '<em>CELLRANGE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CELLRANGE</em>'.
   * @generated
   */
  CELLRANGE createCELLRANGE();

  /**
   * Returns a new object of class '<em>MATHUNIT</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MATHUNIT</em>'.
   * @generated
   */
  MATHUNIT createMATHUNIT();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MyDslPackage getMyDslPackage();

} //MyDslFactory
