/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Nr Columns</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.NrColumns#getNr <em>Nr</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNrColumns()
 * @model
 * @generated
 */
public interface NrColumns extends EObject
{
  /**
   * Returns the value of the '<em><b>Nr</b></em>' attribute list.
   * The list contents are of type {@link java.lang.Integer}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nr</em>' attribute list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNrColumns_Nr()
   * @model unique="false"
   * @generated
   */
  EList<Integer> getNr();

} // NrColumns
