/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PRIM</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PRIM#getMathunit <em>Mathunit</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PRIM#getAdd <em>Add</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPRIM()
 * @model
 * @generated
 */
public interface PRIM extends EObject
{
  /**
   * Returns the value of the '<em><b>Mathunit</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mathunit</em>' containment reference.
   * @see #setMathunit(MATHUNIT)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPRIM_Mathunit()
   * @model containment="true"
   * @generated
   */
  MATHUNIT getMathunit();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PRIM#getMathunit <em>Mathunit</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mathunit</em>' containment reference.
   * @see #getMathunit()
   * @generated
   */
  void setMathunit(MATHUNIT value);

  /**
   * Returns the value of the '<em><b>Add</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Add</em>' containment reference.
   * @see #setAdd(ADD)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPRIM_Add()
   * @model containment="true"
   * @generated
   */
  ADD getAdd();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PRIM#getAdd <em>Add</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Add</em>' containment reference.
   * @see #getAdd()
   * @generated
   */
  void setAdd(ADD value);

} // PRIM
