/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SUB</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SUB#getMult1 <em>Mult1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SUB#getMult2 <em>Mult2</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSUB()
 * @model
 * @generated
 */
public interface SUB extends EObject
{
  /**
   * Returns the value of the '<em><b>Mult1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mult1</em>' containment reference.
   * @see #setMult1(MULT)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSUB_Mult1()
   * @model containment="true"
   * @generated
   */
  MULT getMult1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.SUB#getMult1 <em>Mult1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mult1</em>' containment reference.
   * @see #getMult1()
   * @generated
   */
  void setMult1(MULT value);

  /**
   * Returns the value of the '<em><b>Mult2</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.MULT}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mult2</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSUB_Mult2()
   * @model containment="true"
   * @generated
   */
  EList<MULT> getMult2();

} // SUB
