/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>VALUE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.VALUE#getString <em>String</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.VALUE#getExpr <em>Expr</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.VALUE#getMath <em>Math</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.VALUE#getRange <em>Range</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getVALUE()
 * @model
 * @generated
 */
public interface VALUE extends EObject
{
  /**
   * Returns the value of the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>String</em>' attribute.
   * @see #setString(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getVALUE_String()
   * @model
   * @generated
   */
  String getString();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.VALUE#getString <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String</em>' attribute.
   * @see #getString()
   * @generated
   */
  void setString(String value);

  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(ADD)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getVALUE_Expr()
   * @model containment="true"
   * @generated
   */
  ADD getExpr();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.VALUE#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(ADD value);

  /**
   * Returns the value of the '<em><b>Math</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Math</em>' attribute.
   * @see #setMath(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getVALUE_Math()
   * @model
   * @generated
   */
  String getMath();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.VALUE#getMath <em>Math</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Math</em>' attribute.
   * @see #getMath()
   * @generated
   */
  void setMath(String value);

  /**
   * Returns the value of the '<em><b>Range</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Range</em>' containment reference.
   * @see #setRange(CELLRANGE)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getVALUE_Range()
   * @model containment="true"
   * @generated
   */
  CELLRANGE getRange();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.VALUE#getRange <em>Range</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Range</em>' containment reference.
   * @see #getRange()
   * @generated
   */
  void setRange(CELLRANGE value);

} // VALUE
