/*
 * generated by Xtext 2.42.0
 */
package org.example.domainmodel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DomainModelUiModule extends AbstractDomainModelUiModule {

	public DomainModelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
