/*
 * generated by Xtext 2.42.0
 */
package org.example.domainmodel;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DomainModelStandaloneSetup extends DomainModelStandaloneSetupGenerated {

	public static void doSetup() {
		new DomainModelStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
