/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.mydsl.generator;

import com.google.common.collect.Iterators;
import java.util.ArrayList;
import java.util.HashMap;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.Conversions;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.xtext.example.mydsl.myDsl.ADD;
import org.xtext.example.mydsl.myDsl.Column;
import org.xtext.example.mydsl.myDsl.DIVID;
import org.xtext.example.mydsl.myDsl.MATHUNIT;
import org.xtext.example.mydsl.myDsl.MULT;
import org.xtext.example.mydsl.myDsl.PRIM;
import org.xtext.example.mydsl.myDsl.SUB;
import org.xtext.example.mydsl.myDsl.Table;
import org.xtext.example.mydsl.myDsl.VALUE;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class MyDslGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    final Function1<Table, Boolean> _function = (Table it) -> {
      return Boolean.valueOf(true);
    };
    final Table table = IteratorExtensions.<Table>findFirst(Iterators.<Table>filter(resource.getAllContents(), Table.class), _function);
    final ArrayList<ArrayList<String>> rows = this.getRowData(table);
    fsa.generateFile("greetings.txt", this.compile(table, rows));
  }

  private String getCellRef(final int int1, final int int2) {
    final String line = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    char _charAt = line.charAt(int1);
    String _string = Integer.valueOf(int2).toString();
    String ref = (Character.valueOf(_charAt) + _string);
    return ref;
  }

  private ArrayList<ArrayList<String>> getRowData(final Table table) {
    final HashMap<String, VALUE> unevaluatedcellref = new HashMap<String, VALUE>();
    {
      int i = 0;
      int _length = ((Object[])Conversions.unwrapArray(table.getColumns(), Object.class)).length;
      boolean _lessThan = (i < _length);
      boolean _while = _lessThan;
      while (_while) {
        {
          int j = 0;
          int _length_1 = ((Object[])Conversions.unwrapArray(table.getColumns().get(i).getCell(), Object.class)).length;
          boolean _lessThan_1 = (j < _length_1);
          boolean _while_1 = _lessThan_1;
          while (_while_1) {
            {
              final String cellref = this.getCellRef(i, (1 + j));
              unevaluatedcellref.put(cellref, table.getColumns().get(i).getCell().get(j).getValue());
            }
            int _j = j;
            j = (_j + 1);
            int _length_2 = ((Object[])Conversions.unwrapArray(table.getColumns().get(i).getCell(), Object.class)).length;
            boolean _lessThan_2 = (j < _length_2);
            _while_1 = _lessThan_2;
          }
        }
        int _i = i;
        i = (_i + 1);
        int _length_1 = ((Object[])Conversions.unwrapArray(table.getColumns(), Object.class)).length;
        boolean _lessThan_1 = (i < _length_1);
        _while = _lessThan_1;
      }
    }
    final ArrayList<ArrayList<String>> outerArrayList = new ArrayList<ArrayList<String>>();
    {
      int i = 0;
      int _length = ((Object[])Conversions.unwrapArray(table.getColumns(), Object.class)).length;
      boolean _lessThan = (i < _length);
      boolean _while = _lessThan;
      while (_while) {
        {
          final ArrayList<String> row = new ArrayList<String>();
          {
            int j = 0;
            int _length_1 = ((Object[])Conversions.unwrapArray(table.getColumns().get(i).getCell(), Object.class)).length;
            boolean _lessThan_1 = (j < _length_1);
            boolean _while_1 = _lessThan_1;
            while (_while_1) {
              row.add(this.cellValueEvaluator(table.getColumns().get(i).getCell().get(j).getValue(), unevaluatedcellref));
              int _j = j;
              j = (_j + 1);
              int _length_2 = ((Object[])Conversions.unwrapArray(table.getColumns().get(i).getCell(), Object.class)).length;
              boolean _lessThan_2 = (j < _length_2);
              _while_1 = _lessThan_2;
            }
          }
          outerArrayList.add(row);
        }
        int _i = i;
        i = (_i + 1);
        int _length_1 = ((Object[])Conversions.unwrapArray(table.getColumns(), Object.class)).length;
        boolean _lessThan_1 = (i < _length_1);
        _while = _lessThan_1;
      }
    }
    return this.transpose(outerArrayList);
  }

  private String compile(final Table table, final ArrayList<ArrayList<String>> rows) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("\\begin{tabular}{ |");
    {
      EList<Column> _columns = table.getColumns();
      for(final Column col : _columns) {
        _builder.append("c|");
      }
    }
    _builder.append(" }");
    _builder.newLineIfNotEmpty();
    {
      for(final ArrayList<String> row : rows) {
        _builder.append("\\hline");
        _builder.newLine();
        _builder.append("    ");
        {
          boolean _hasElements = false;
          for(final String cell : row) {
            if (!_hasElements) {
              _hasElements = true;
            } else {
              _builder.appendImmediate(" & ", "    ");
            }
            _builder.append(cell, "    ");
          }
        }
        _builder.append(" \\\\");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("\\hline");
    _builder.newLine();
    _builder.append("\\end{tabular}");
    _builder.newLine();
    return _builder.toString();
  }

  private String cellValueEvaluator(final VALUE value, final HashMap<String, VALUE> valueMap) {
    String _string = value.getString();
    boolean _tripleNotEquals = (_string != null);
    if (_tripleNotEquals) {
      return value.getString();
    } else {
      return Float.valueOf(this.addEval(value.getExpr(), valueMap)).toString();
    }
  }

  public float addEval(final ADD add, final HashMap<String, VALUE> valueMap) {
    float result = this.subEval(add.getSub1(), valueMap);
    EList<SUB> _sub2 = add.getSub2();
    for (final SUB s : _sub2) {
      float _subEval = this.subEval(s, valueMap);
      float _plus = (result + _subEval);
      result = _plus;
    }
    return result;
  }

  public float subEval(final SUB sub, final HashMap<String, VALUE> valueMap) {
    float result = this.multEval(sub.getMult1(), valueMap);
    EList<MULT> _mult2 = sub.getMult2();
    for (final MULT m : _mult2) {
      float _multEval = this.multEval(m, valueMap);
      float _minus = (result - _multEval);
      result = _minus;
    }
    return result;
  }

  public float multEval(final MULT mult, final HashMap<String, VALUE> valueMap) {
    float result = this.dividEval(mult.getDivid1(), valueMap);
    EList<DIVID> _divid2 = mult.getDivid2();
    for (final DIVID d : _divid2) {
      float _dividEval = this.dividEval(d, valueMap);
      float _multiply = (result * _dividEval);
      result = _multiply;
    }
    return result;
  }

  public float dividEval(final DIVID divid, final HashMap<String, VALUE> valueMap) {
    float result = this.primEval(divid.getPrim1(), valueMap);
    EList<PRIM> _prim2 = divid.getPrim2();
    for (final PRIM p : _prim2) {
      float _primEval = this.primEval(p, valueMap);
      float _divide = (result / _primEval);
      result = _divide;
    }
    return result;
  }

  public float primEval(final PRIM prim, final HashMap<String, VALUE> valueMap) {
    MATHUNIT _mathunit = prim.getMathunit();
    boolean _tripleNotEquals = (_mathunit != null);
    if (_tripleNotEquals) {
      return this.mathunitEval(prim.getMathunit(), valueMap);
    } else {
      return this.addEval(prim.getAdd(), valueMap);
    }
  }

  public float mathunitEval(final MATHUNIT mathunit, final HashMap<String, VALUE> valueMap) {
    String _cellref = mathunit.getCellref();
    boolean _tripleNotEquals = (_cellref != null);
    if (_tripleNotEquals) {
      return this.addEval(valueMap.get(mathunit.getCellref()).getExpr(), valueMap);
    } else {
      return mathunit.getNumber();
    }
  }

  private ArrayList<ArrayList<String>> transpose(final ArrayList<ArrayList<String>> matrixIn) {
    ArrayList<ArrayList<String>> matrixOut = new ArrayList<ArrayList<String>>();
    boolean _isEmpty = matrixIn.isEmpty();
    boolean _not = (!_isEmpty);
    if (_not) {
      int noOfElementsInList = matrixIn.get(0).size();
      for (int i = 0; (i < noOfElementsInList); i++) {
        {
          ArrayList<String> col = new ArrayList<String>();
          for (final ArrayList<String> row : matrixIn) {
            col.add(row.get(i));
          }
          matrixOut.add(col);
        }
      }
    }
    return matrixOut;
  }
}
