/*
 * generated by Xtext 2.41.0
 */
package org.example.domainmodel.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDomainModelScopeProvider extends DelegatingScopeProvider {
}
