/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.mydsl.validation

import org.eclipse.xtext.nodemodel.util.NodeModelUtils
import org.eclipse.xtext.validation.Check
import org.xtext.example.mydsl.myDsl.MATHUNIT
import org.xtext.example.mydsl.myDsl.MyDslPackage
import org.xtext.example.mydsl.myDsl.SystemRoot
import org.xtext.example.mydsl.myDsl.Table

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class MyDslValidator extends AbstractMyDslValidator {
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

    public static val FORWARD_REFERENCE = 'forwardReference';
    public static val DUPLICATE_VAR = 'duplicateVar';
    public static val INVALID_NAME = 'invalidName';
    public static val MISSING_TABLE = 'missingTable';
    public static val MISSING_COLUMN = 'missingColumn';

    @Check
    def checkTableNameStartsWithCapital(Table table) {
        if (!Character.isUpperCase(table.name.charAt(0))) {
            warning('Table name should start with a capital',
            MyDslPackage.Literals.TABLE__NAME,
            INVALID_NAME)
        }
    }

    @Check
    def checkNoDuplicateVarsInTable(Table table) {
        val names = newHashSet
        for (v : table.vars) {
            if (!names.add(v.name)) {
                error('Duplicate variable "' + v.name + '" in table',
                v,
                MyDslPackage.Literals.LET_DECLARATION__NAME,
                DUPLICATE_VAR)
            }
        }
    }

	//Iteration over SystemRoot
	@Check
	def checkNoDuplicateVarsInRoot(SystemRoot root) {
	    val names = newHashSet
	    for (v : root.vars) {
	        if (!names.add(v.name)) {
	            error('Duplicate variable "' + v.name + '" in global scope',
	            v,
	            MyDslPackage.Literals.LET_DECLARATION__NAME,
	            DUPLICATE_VAR)
	        }
	    }
	}

	@Check
	def checkAtLeastOneTable(SystemRoot root) {
	    if (root.tables === null || root.tables.isEmpty) {
	        error('A Model must contain at least one table',
	        MyDslPackage.Literals.SYSTEM_ROOT__TABLES,
	        MISSING_TABLE)
	    }
    }

    @Check
    def checkAtLeastOneColumn(Table table) {
        if (table.columns === null || table.columns.empty) {
            error('Table "' + table.name + '" must contain at least one column',
            MyDslPackage.Literals.TABLE__COLUMNS,
            MISSING_COLUMN)
        }
    }

	//Custom Check on making sure that forward references are not allowed.
	@Check
	def checkNoForwardReferences(MATHUNIT unit) {
	    if (unit.varRef === null) return

	    val unitOffset = NodeModelUtils.getNode(unit).offset
        val varOffset  = NodeModelUtils.getNode(unit.varRef).offset

        if (varOffset > unitOffset) {
            error('Forward Reference is not allowed: "' + unit.varRef.name + '" is defined later',
            MyDslPackage.Literals.MATHUNIT__VAR_REF,
            FORWARD_REFERENCE)
        }
	}
}
